### ISSUE TITLE
Restrict Sunday is the first day for the week.

### ISSUE THREAD

**Issue by The-RobinHood** [square/android-times-square#118]
I'm trying to display calendar in french language, its show Monday as first week but I need to change Sunday.

Code to show calendar in specific language using Locale.

```
calendar.init(startdate, enddate, Locale.FRENCH)
        .inMode(SelectionMode.SINGLE).withSelectedDate(new Date());
```

I tried to change `MonthView` but no luck, will you please shed the light on the same?

**Comment by hermannloose** [comment]
The first day of the week is separately configurable through `Calendar.setFirstDayOfWeek()`. All Calendar instances used by the library seem to be constructed from the locale in `CalendarPickerView.init(Date minDate, Date maxDate, Locale locale)`, so it should be feasible to add the option to override this in one central place.
