### ISSUE TITLE
Can months be displayed in a  viewpager instead of a scrollview?

### ISSUE THREAD

**Issue by freedom2013** [square/android-times-square#131]
New comer here!
I would like to see that if the months can be displayed in a  viewpager,
or any configuration I can set?

**Comment by ssuresh1295** [comment]
Hi, can we change this ListView to viewpager. Is there any possibilities.

**Comment by BKChandan** [comment]
Hi,

I have not tried. But I believe this can be implemented as view pager.

Thanks
Chandan

**Comment by ssuresh1295** [comment]
can you tell me any tips to do with viewpager. :)
