### ISSUE TITLE
validateDate should be declared with throws IllegalArgumentException

### ISSUE THREAD

**Issue by espiegel** [square/android-times-square#178]
Fatal Exception: java.lang.IllegalArgumentException
SelectedDate must be between minDate and maxDate. minDate: Sun Feb 02 00:00:00 GMT+02:00 2014 maxDate: Mon Feb 01 23:59:00 GMT+02:00 2016 selectedDate: Sat Jan 12 00:00:00 GMT+02:00 2013

Since the validateTime method doesn't declare that it throws exceptions its fairly easy for these exceptions to go uncaught and crash apps.

What this means is that all methods that call validateTime() will also need to declare that they throw an exception. So for example selectDate() and highlightDates() will need to declare that they throw an exception which makes sense if you gave them a bad date argument.

This change will let developers know that they need to handle these exceptions and will lower the amount of crashes.

**Comment by espiegel** [comment]
Actually it should be a checked Exception and not a RuntimeException

**Comment by JakeWharton** [comment]
This will not be changed to a checked exception. At worst this is a missing
Javadoc problem.
