### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by AAverin** [square/android-times-square#181]
Hi guys.
Really like your library.

Any way I can make it respect timezones?
Date object by default is converted to the timezone that is selected on the device, and while you accept Dates in the init() method, what would be the correct way to change timezone for the widget?
In my usecase I need to display all dates and times in the UI in the specific timezone.
Calendar widget not respecting timzones results in time shifts in my project, for example, picking 16th of February after conversions become 15th.

**Comment by edenman** [comment]
We don't do any timezone stuff in the library.  You'll just have to translate from the user's timezone to UTC or whatever you're expecting.

**Comment by AAverin** [comment]
ok, so UI will be always UTC?

**Comment by edenman** [comment]
UI is in the user's timezone (we just use `Calendar.getInstance()`)

**Comment by AAverin** [comment]
I see. So looks like I will need to do -offset before passing initial dates to your calendar, and +offset when I get them back
