### ISSUE TITLE
Picking date range of 1 day

### ISSUE THREAD

**Issue by AAverin** [square/android-times-square#182]
Sorry if this issue might have already been mentioned.
I need to be able to pick the same day as start and end date in the calendar.
How can I achieve that?

**Comment by edenman** [comment]
Just set the minDate and maxDate to the date you want.

**Comment by AAverin** [comment]
I think you misunderstood the question.
I set minDate and maxDate to a very large range of dates.
But I still want to be able to pick in the UI the same day as both the beginning and end.

To give a real use-case - user rents a car, he picks dates in the UI made by your calendar. But he wants to pick and return a car at the same day. Get it in the morning, and return in the evening.

**Comment by edenman** [comment]
Ah.  Not currently supported.  I think you're probably just better off forking for this, you'll need some custom UI to indicate that that cell is double-selected and I don't think most `RANGE` usecases need what you want.
