### ISSUE TITLE
clearOldSelections() doesn't invoke onDateUnselected listener

### ISSUE THREAD

**Issue by AAverin** [square/android-times-square#184]
As title says.
Would be good to know when all dates are unselected.
Maybe not as part of onDateUnselected call, but maybe a separate method, onDatesCleared, for example.

**Comment by edenman** [comment]
I think it makes sense to have it just call onDateUnselected.  If you want to make that PR I'll gladly accept it.  Should probably add a test for that case (the RANGE unselection) too.
