### ISSUE TITLE
Add few content associate with date

### ISSUE THREAD

**Issue by chiragjain** [square/android-times-square#187]
I want to add some extra content like number of hours on each date. Like image shown below : [calendar_cropped](https://cloud.githubusercontent.com/assets/4264236/6370864/3271cbc2-bd1b-11e4-9016-348701105d4b.png)

**Comment by Vovaxo** [comment]
You need to use your custom Decorator class which implements CalendarCellDecorator interface. There is an example of usage custom decorator class in the sample project

**Comment by chiragjain** [comment]
New Release on Gradle?

**Comment by chiragjain** [comment]
Sorry, but i am not able to use decorator using gradle. Please help.

**Comment by JakeWharton** [comment]
We have no made a release since it was merged. You will have to wait for
the next release.

**Comment by MAW016** [comment]
And when it will be? :)
