### ISSUE TITLE
Don't display dates from other months

### ISSUE THREAD

**Issue by burntcookie90** [square/android-times-square#194]
Is there a way to not display cells that don't exist in the month? For example: 
![timessquarescreenshot](https://cloud.githubusercontent.com/assets/1452613/6677871/f16531fa-cc01-11e4-80dc-4849580dabad.png)

**Comment by burntcookie90** [comment]
Nevermind, I've just exposed `isCurrentMonth` on `CalendarCellView` to set the cell visibility.

**Comment by JakeWharton** [comment]
This would be a good feature is there's an adjoining month.

**Comment by burntcookie90** [comment]
I can look into making a PR for it then
