### ISSUE TITLE
Impossible to set new Date(0) as selected date

### ISSUE THREAD

**Issue by smaspe** [square/android-times-square#196]
It results in the exception:

    java.lang.IllegalArgumentException: Selected date must be non-zero.  Wed Dec 31 14:00:00 HST 1969

In some case it is actually a valid input.

**Comment by edenman** [comment]
In which case is this valid?

**Comment by smaspe** [comment]
any case where you want to select the 1/1/1970 on the calendar. (more so if your timezone is +0)

**Comment by edenman** [comment]
Ok, I'll buy that.  Can you give me some more context on what you're trying to accomplish?  If you're showing a CalendarPickerView with the last fifty years in it, you're going to have some _serious_ performance issues with our current implementation.

**Comment by edenman** [comment]
(Regardless, PRs welcome to remove the 0 check)

**Comment by smaspe** [comment]
That is actually what I was trying to do in the first place. (not anymore, though, both for performances and practicality reasons, so I can probably live without the fix.). I'll PR during the week when I have 2 minutes to look at it.

**Comment by smaspe** [comment]
Took a little longer to find those 2 minutes, but the PR is in.
