### ISSUE TITLE
Highlighted dates color

### ISSUE THREAD

**Issue by yakivmospan** [square/android-times-square#198]
Hi guys,

thanks for great work done here. Could you tell me please if is there possibility to change highlighted dates color without pulling sources and changing it in `colors.xml`. I can't find open API for it.

Also It would be nice to have something like:
```java
        mPickerView.highlightDates(dates, color);
``` 
to set different colors for different highlighted dates.

Thanks,
Yakiv

**Comment by edenman** [comment]
Two options: 

- you can simply override the highlighted color in your app's colors.xml (just use the same resource name).
- use the cell decorator support added in: https://github.com/square/android-times-square/pull/180

**Comment by IrinaGabrielaNuta** [comment]
Can we have multiple types of hightlited dates? I'm talking about different colors for those types of dates.

**Comment by edenman** [comment]
Use a cell decorator and you can do whatever you want.
