### ISSUE TITLE
Detect Scrolling

### ISSUE THREAD

**Issue by malvin91** [square/android-times-square#199]
I have implemented your code, but I am unable to detect the event when the month change. I have to highlight the range of dates from months. Since multiple range selection is not possible. Please Help!
![device-2015-04-02-175258](https://cloud.githubusercontent.com/assets/6801363/6963834/267c3372-d961-11e4-8d1b-b9ea96c08db4.png)

**Comment by edenman** [comment]
You can use the new `CalendarCellDecorator` to highlight ranges in multiple months.

**Comment by emce** [comment]
CalendarCellDecorator is also working just for current month (see screenshot below)
![calendarcelldecorator](https://cloud.githubusercontent.com/assets/842099/7221777/879df456-e6f9-11e4-822b-225ee968ff61.png)

**Comment by malvin91** [comment]
can you guys show via code, since I am not getting it completely  :)

**Comment by emce** [comment]
This is my decorator - I've check data twice - there are data for couple of months, and the cells are marked just in current.
```
public class MonthDecorator implements CalendarCellDecorator {

    private ArrayList<LocalDate> mSchedules = new ArrayList<>();
    private ArrayList<LocalDate> mOffers = new ArrayList<>();

    public MonthDecorator(LocalDate[] schedules, LocalDate[] offers) {
        if (schedules != null) {
            mSchedules.addAll(Arrays.asList(schedules));
        }
        if (offers != null) {
            mOffers.addAll(Arrays.asList(offers));
        }
    }

    @Override
    public void decorate(CalendarCellView calendarCellView, Date date) {
        LocalDate localDate = new LocalDate(date);
        if (mOffers.contains(localDate) && mSchedules.contains(localDate)) {
            calendarCellView.setBackgroundResource(R.drawable.cell_both_dots);
        } else if (mSchedules.contains(localDate) && !mOffers.contains(localDate)) {
            calendarCellView.setBackgroundResource(R.drawable.cell_blue_dot);
        } else if (!mSchedules.contains(localDate) && mOffers.contains(localDate)) {
            calendarCellView.setBackgroundResource(R.drawable.cell_green_dot);
        }
    }
}
```

**Comment by malvin91** [comment]
This is the way I have done but, I am unable to detect when month got changed while scrolling 

code:

       try {

					JSONArray array=new JSONArray(response);
					for (int i = 0; i < array.length(); i++) {
						
						JSONObject json=array.getJSONObject(i);
						list.add(json.getString("fromDate")+" "+json.getString("toDate"));
						
					}
					
					SimpleDateFormat sdf =  new SimpleDateFormat("yyyy-MM-dd");
					TimeZone gmt = TimeZone.getTimeZone("GMT");
					sdf.setTimeZone(gmt);
					sdf.setLenient(false);

					try {
					    Date date = sdf.parse(list.get(0).split(" ")[0]);
					    Date date1 = sdf.parse(list.get(0).split(" ")[1]);
					    System.out.println(date);
					    dates.add(date);
					    dates.add(date1);
					} catch (Exception e) {
					    e.printStackTrace();
					}					
				    
					calendar.init(lastYear.getTime(), nextYear.getTime()).inMode(SelectionMode.RANGE).withSelectedDates(dates);				

				} catch (JSONException e) {
					e.printStackTrace();

				}

thanks for fast reply :)
