### ISSUE TITLE
Making the sources gradle-compatible

### ISSUE THREAD

**Issue by MarKco** [square/android-times-square#202]
Hello everybody,
it seems like sources are not good for importation in Android Studio because they miss all the .gradle files.

**Comment by JakeWharton** [comment]
The project builds with Maven so it won't work in Android Studio. We are pushing an aar so it's compatible on the consuming side which is where it matters. Maybe we switch some day, but it isn't really an issue.

**Comment by MarKco** [comment]
Ok, makes sense.
Don't know if that's interesting for you, anyway I managed to import it in Android Studio as sources library (by creating a new library and copying inside the android-times-square folders). Maybe just adding the build.gradle files you could make it compatible?

If you want me I can send you an archive with the whole folder in it.

Thank you for your patience and for this great library!

**Comment by JakeWharton** [comment]
We're well versed with both build systems. Gradle is much worse for project management than Maven which is why we'll cling to it everywhere we can in open source land. Sadly this project would benefit from switching, so it'll probably happen eventually.

**Comment by MarKco** [comment]
Fair enough! Thank you!
