### ISSUE TITLE
Cannot access clearHighlightedDates() in TimesSquare CalendarPickerView

### ISSUE THREAD

**Issue by wbdeveloper123** [square/android-times-square#203]
Using thro Gradle  compile 'com.squareup:android-times-square:1.5.0@aar'

//this works  - wgere calendar is instance of CalendarPickerView
calendar.highlightDates(higlightedDateList);  

//this doesn't work   -- Cannot resolve 'clearHighlightedDates()'
calendar.clearHighlightedDates();

--  For now I am re-initializing the calendar again

**Comment by edenman** [comment]
`clearHighlightedDates()` was added in 1.6.0
