### ISSUE TITLE
How to Change Highlighted Dates Color?

### ISSUE THREAD

**Issue by javagc** [square/android-times-square#204]
Hi, Highlighted Dates color is green , How to customize it?

**Comment by javagc** [comment]
I am sorry for this , I have found answer myself.

There is color with code calendar_highlighted_day_bg, just added this line in your color.xml file


<color name="calendar_highlighted_day_bg">YOUR_COLOR</color>


also ther are other colors


  <color name="calendar_active_month_bg">#fff5f7f9</color>
  <color name="calendar_bg">#ffffffff</color>
  <color name="calendar_divider">#ffbababa</color>
  <color name="calendar_inactive_month_bg">#ffd7d9db</color>
  <color name="calendar_selected_day_bg">#ff379bff</color>
  <color name="calendar_highlighted_day_bg">#ccffcc</color>
  <color name="calendar_selected_range_bg">#ff96caff</color>
  <color name="calendar_text_inactive">#40778088</color>
  <color name="calendar_text_active">#ff778088</color>
  <color name="calendar_text_selected">#ffffffff</color>
  <color name="calendar_text_unselectable">#7f778088</color>

**Comment by jainakhil88** [comment]
thanks, that helped!

**Comment by nure-nabi** [comment]
thanks bro

**Comment by nure-nabi** [comment]
multiple highlited color how we can do this works

**Comment by praveen1256** [comment]
Hi if i tried to change the color in colors.xml its not reflecting. can you please help on this

**Comment by praveen1256** [comment]
I got it thanks
