### ISSUE TITLE
lisner on month scrolling 

### ISSUE THREAD

**Issue by malvin91** [square/android-times-square#205]
I have implemented your code, but I am unable to detect the event when the month change. I have to highlight the range of dates from months. Since multiple range selection is not possible. Please Help!
![device-2015-04-02-175258](https://cloud.githubusercontent.com/assets/6801363/6963834/267c3372-d961-11e4-8d1b-b9ea96c08db4.png)

code

    
				try {

					JSONArray array=new JSONArray(response);
					for (int i = 0; i < array.length(); i++) {
						
						JSONObject json=array.getJSONObject(i);
						list.add(json.getString("fromDate")+" "+json.getString("toDate"));
						
					}
					
					SimpleDateFormat sdf =  new SimpleDateFormat("yyyy-MM-dd");
					TimeZone gmt = TimeZone.getTimeZone("GMT");
					sdf.setTimeZone(gmt);
					sdf.setLenient(false);

					for (int i = 0; i < list.size(); i++) {					
					try {
					    Date date = sdf.parse(list.get(i).split(" ")[0]);
					    Date date1 = sdf.parse(list.get(i).split(" ")[1]);
					    
					    if (i==0) {
						    dates1.add(date);
						    dates1.add(date1);	
						    calender1.init(lastYear.getTime(), nextYear.getTime()).inMode(SelectionMode.RANGE).withSelectedDates(dates1);
						}

					    if (i==1) {
						    dates2.add(date);
						    dates2.add(date1);	
						    calender2.init(lastYear.getTime(), nextYear.getTime()).inMode(SelectionMode.RANGE).withSelectedDates(dates2);
						}
					    
					    if (i==2) {
						    dates3.add(date);
						    dates3.add(date1);	
						    calender3.init(lastYear.getTime(), nextYear.getTime()).inMode(SelectionMode.RANGE).withSelectedDates(dates3);
						}
					    
					    
					    if (i==3) {
						    dates4.add(date);
						    dates4.add(date1);
						    calender4.init(lastYear.getTime(), nextYear.getTime()).inMode(SelectionMode.RANGE).withSelectedDates(dates4);
						    
						}
					    
					    
					    if (i==4) {
						    dates5.add(date);
						    dates5.add(date1);	
						    calender5.init(lastYear.getTime(), nextYear.getTime()).inMode(SelectionMode.RANGE).withSelectedDates(dates5);
						    
						}
					    
					    
					    
					} catch (Exception e) {
					    e.printStackTrace();
					}					
					}
									

				} catch (JSONException e) {
					e.printStackTrace();

				}

**Comment by edenman** [comment]
Dup of #199

**Comment by malvin91** [comment]
@edenman its dup but I haven't got any way to do so.

have you seen my code?

**Comment by emce** [comment]
Both this and https://github.com/square/android-times-square/issues/199 - will this issue be fixed?

**Comment by malvin91** [comment]
> No not yet !!!
