### ISSUE TITLE
How to Implement setOnDateLongClickListener()....

### ISSUE THREAD

**Issue by FranciscoJavierPRamos** [square/android-times-square#207]

**Comment by edenman** [comment]
set up a `CalendarCellDecorator`

**Comment by FranciscoJavierPRamos** [comment]
That worked for me , but when I add the decorator , the application slows down. Any solution?

Thanks anyway.

**Comment by edenman** [comment]
@FranciscoJavierPRamos what does your decorator look like?  Try adding logging that measures System.currentTimeMillis at the beginning of your decorator and at the end to see how long it's taking each time.

**Comment by FranciscoJavierPRamos** [comment]
This is my decorator:


.....

        long initialTime = System.currentTimeMillis();

        String dateString = Integer.toString(date.getDate());
        SpannableString string = new SpannableString(dateString);

        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");

        String d = df.format(date);

        if(d.equals("25/04/2015")){
            SpannableString stringDate = new SpannableString(dateString + "\nJunta");
            stringDate.setSpan(new RelativeSizeSpan(0.5f), 0, dateString.length(),
                    Spanned.SPAN_INCLUSIVE_EXCLUSIVE);
            cellView.setText(stringDate);
            //cellView.setSelected(true);
            cellView.setBackgroundColor(Color.parseColor("#3a9bdc"));
            cellView.setTextColor(Color.parseColor("#FFFFFF"));
            cellView.setEvent(true);

        }else {
            cellView.destroyDrawingCache();
            string.setSpan(new RelativeSizeSpan(1.1f), 0, dateString.length(),
                    Spanned.SPAN_INCLUSIVE_EXCLUSIVE);
            cellView.setText(string);
            cellView.setEvent(false);
            if(cellView.isToday() == false){
                cellView.setBackground(getContext().getResources().getDrawable(R.drawable.custom_calendar_bg_selector_rectangle));
            }

        }

        cellView.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                showCellDialog(v, cellView);
                return false;
            }
        });

        long finalTime = System.currentTimeMillis();

        //long totalTime = finalTime - initialTime;
        Toast.makeText(getContext(), "Start Time: " + initialTime + "\nFinal Time: " + String.valueOf(finalTime), Toast.LENGTH_SHORT).show();
    }
.
.
.
.

Screenshots:

![screenshot_2015-04-24-14-59-26](https://cloud.githubusercontent.com/assets/7097754/7327454/edc01042-ea92-11e4-93d8-1798098d9878.png)

The difference is: 1


But in this screenshot, the difference is: 2:
![screenshot_2015-04-24-15-00-15](https://cloud.githubusercontent.com/assets/7097754/7327482/25aa45d6-ea93-11e4-8f95-88c356b094ef.png)

**Comment by edenman** [comment]
Ha.  Way to not mention that you're completely changing the layout of _every_ cell you decorate.  You need to figure out a way to only force a relayout when you're actually changing something.

**Comment by FranciscoJavierPRamos** [comment]
This is the output whenever a month creates:

04-24 16:21:03.061  21422-21422/timesheet.dcubica.com.ats D/TimesSquare﹕ Initializing MonthView (1116404872) for MonthDescriptor{label='septiembre 2015', month=8, year=2015}

04-24 16:21:03.104  21422-21422/timesheet.dcubica.com.ats D/TimesSquare﹕ MonthView.init took 43 ms

04-24 16:21:03.104  21422-21422/timesheet.dcubica.com.ats D/TimesSquare﹕ Grid.onMeasure w=MeasureSpec: EXACTLY 656 h=MeasureSpec: UNSPECIFIED 0

04-24 16:21:03.104  21422-21422/timesheet.dcubica.com.ats D/TimesSquare﹕ SKIP Grid.onMeasure

04-24 16:21:03.108  21422-21422/timesheet.dcubica.com.ats D/TimesSquare﹕ Grid.onLayout 0 ms
