### ISSUE TITLE
Trying to change state of week days CalendarCellViews (mon, tue, wed...)

### ISSUE THREAD

**Issue by deionalims** [square/android-times-square#210]
Hello,

I'm trying to change the state of the week days CalendarCellViews. I added a listener on the header row so that when the user clicks on monday it selects all the monday cells. 
Though I can't manage to change the state of the "monday cell". I go through the CalendarCellViews of the header row in MonthView.init() method and I change the state of those views exactly like it's done for the other CalendarCellViews but the method onCreateDrawableState() is never called even though refreshDrawableState() is called when I change the state of the view.
There is obviously a reason why it works for the day cells and not for the weekday cells but I couldn't find out why. 

Thanks for any help.

FX

**Comment by edenman** [comment]
@deionalims the header views aren't `CalendarCellView`s, they're just `TextView`s.  Check out `month.xml`

**Comment by deionalims** [comment]
@edenman Thanks for the reply.

Indeed the header views are TextViews though I forgot to mention that I switched them into CalendarCellViews in order to benefit the different state changes. Is there something more I need to do to enable the state changes on those cells ?

Thanks.

**Comment by deionalims** [comment]
OK I found the issue. 
In the method setDayBackground(int resId) of CalendarGridView.java, the index starts at 1. The property mBackground of the children of the first row was null instead of being a StateListDrawable. 
Starting from index 0 fixed the issue. I can now change the state of the cells of the header row of each month. 

I hope this will help others in my case.
