### ISSUE TITLE
How do I change the color of highlited dates programatically?

### ISSUE THREAD

**Issue by basit-saeed** [square/android-times-square#217]
Is there a way to set multiple colors, too? I want two set of events with different colors.
Like

//A function to set certain color to the following collection of dates.
calendar.highlightDates(highLightedDates);

//Call the color function and change the color through it to apply on following collection of dates.
calendar.highlightDates(highLightedDates2);

**Comment by edenman** [comment]
Hi!  You can use a `CalendarCellDecorator` to apply your custom logic.

**Comment by basit-saeed** [comment]
How do I apply decoration through the ```CalendarCellDecorator``` implementation? I couldn't find an example anywhere.
