### ISSUE TITLE
Dynamically update date selectable filter

### ISSUE THREAD

**Issue by burntcookie90** [square/android-times-square#218]
I'd like to be able to use a single calendar view that "changes state" when selecting the first date vs the second in a range. The first date selection needs to be able to have a different `DateSelectableFilter` than the second selection. Is there any way to accomplish this?

**Comment by edenman** [comment]
Pretty sure you can use a combination of `OnDateSelectedListener` + `getSelectedDates()` to figure out which state you're in, then update your `DateSelectableFilter`.  Might need to figure out a way to force a re-application of your `DateSelectableFilter` (call `init` again?).  

Or you can just use a `CalendarCellDecorator` to apply custom click listeners and manage everything yourself.

**Comment by burntcookie90** [comment]
the latter is what i'm attempting to implement now, thanks for the ideas!
