### ISSUE TITLE
Bad name for today's text color?

### ISSUE THREAD

**Issue by ebabel** [square/android-times-square#223]
Perhaps I misunderstood the intention but in this file: calendar_text_selector.xml
this line:  `<item app:state_today="true" android:color="@color/calendar_active_month_bg"/>`
feels unintentional in its use for setting the background of the today cell. Perhaps a new color should be created? calendar_text_today

Thanks!

**Comment by AAverin** [comment]
Seconded.
It's weird that 'today' calendar date uses the color of the month. When selected date = today - color is overriden and there is not bug present, but if you select another date - today will become a color of the month background, thus invisible.

**Comment by edenman** [comment]
Unfortunately, changing the color names would be a breaking change for anybody who's overriding the colors by defining their own value for `calendar_active_month_bg`.  Doesn't seem like it's worth a breaking change.

**Comment by AAverin** [comment]
This is very strange ruling.
calendar_active_month_bg should and is used as a color for the active month. And users should be able to override it's value however they want. But.
calendar_active_month_bg should not be used as the color of 'today' text in the calendar - it just doesn't make sense.

**Comment by ebabel** [comment]
Why not do an existence check for the new color and fail over to the old attribute?
