### ISSUE TITLE
How i can disable or inactive highlighted dates

### ISSUE THREAD

**Issue by rupeshpatil** [square/android-times-square#224]
Hey,
I want to set list of dates highlighted and want to be inactive(non selectable) on calenders how i can achieve?. Thanks in advance.

**Comment by edenman** [comment]
You can use a `CalendarCellDecorator` to override states on the cells.

**Comment by rupeshpatil** [comment]
Hey edenman, Thanks for your quick reply, I am newbie in android as well in java. How i can override it on calendar init. means how i can get cellview to pass into calendarCell Decorator
