### ISSUE TITLE
Error:(2) Attribute "titleTextColor" has already been defined

### ISSUE THREAD

**Issue by iAviatorJose** [square/android-times-square#232]
I am getting the above error while Gradle Sync.

My Gradle Dependency looks as follows:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.squareup:android-times-square:1.5.0@aar'
}

**Comment by edenman** [comment]
Fixed in #227: update to the latest android-times-square release
