### ISSUE TITLE
getSelectedDates returned zero array after I created the calendar withSelectedDates

### ISSUE THREAD

**Issue by AbigailEsman** [square/android-times-square#245]
Hello,

I created the calendar with "withSelectedDates" function on range mode. Its fine to see the some dates are selected as I expected in calendar UI. But I can't get the selected dates when I didn't any touch in calendar view. I expected to get the selected dates which I passed dates in initialization.

I think initial selected dates should be kept else user didn't touch and it should be returned via "getSelectedDates" function. Can u confirm and fix this issue?

Thanks

**Comment by edenman** [comment]
Sorry for the delayed response.  We have a unit test for this: `testRangeWithTwoInitialSelections` so I'm skeptical that this is a bug in the library.  Closing, feel free to reopen and attach your initialization code if you're still seeing the issue.
