### ISSUE TITLE
Clicking selected cell in RANGE mode should deselect it

### ISSUE THREAD

**Issue by micHar** [square/android-times-square#250]
Clicking selected cell in RANGE mode should deselect it when it's the only cell selected.
1. It feels right, just like in MULTIPLE mode, that you can clear whole selection if you want.
2. I had a specific case where I could only allow ranges which did not have an *unselectable* cell in the middle (a range with only selectable cells). When there was a single *selectable* date between two *unselectable* ones and user selected it, he could do nothing to clear the selection.

I've made necessary changes here https://github.com/micHar/android-times-square/tree/feature/clear-selection and if you think it should be fixed in the lib, I would be glad to make a PR.

**Comment by edenman** [comment]
I have _no_ idea what you're talking about.  Can you give an example of the click events and what you'd like the behavior to be?

**Comment by micHar** [comment]
Yeah, it's difficult to explain and I'm not a native english speaker :).

1. You are in RANGE mode.
2. You click a day (5th of December).
3. You click the same day one more time. As for now it remains selected.

The only way to deselect it is to click a date which is before 5th of December. I think it would be good UX if clicking 5th of December one more time (as long as it remains the only date selected, i.e. the range consists of only one date) would deselect it.

To better understand what I'm talking about, please grab an apk and play with RANGE mode: https://www.dropbox.com/s/bbxuls8dnewzz24/timessquare_deselectable_range.apk?dl=0

**Comment by edenman** [comment]
Seems like a toss-up to me: we don't let you "tap the same date to unselect" in `SINGLE` mode, but we do in `MULTI` mode.  Because there are people out there using `RANGE` mode as it's currently designed, I think we should leave it like it is.  Feel free to fork and change the logic in doSelectDate.  Sorry!
