### ISSUE TITLE
Version 1.6.4 on http://repo1.maven.org contains uncommitted code

### ISSUE THREAD

**Issue by jolros** [square/android-times-square#251]
Hi,

Thanks for the great library!

I was upgrading to 1.6.4 via http://repo1.maven.org/maven2/com/squareup/android-times-square/1.6.4/ and noticed that week.xml and month.xml in [android-times-square-1.6.4.aar](http://repo1.maven.org/maven2/com/squareup/android-times-square/1.6.4/android-times-square-1.6.4.aar) contain comments not found in the github project nor in version 1.6.3 of the archive.

```
</com.squareup.timessquare.CalendarRowView><!-- From: file:/Users/edenman/Development/android-times-square/library/src/main/res/layout/week.xml -->
```

Is this indicative of a build issue? Should I hold off on this upgrade and wait for 1.6.5?

Thanks

**Comment by edenman** [comment]
@jolros looks like this is a bug/feature in the android build, shouldn't affect how this library behaves: https://code.google.com/p/android/issues/detail?id=91151 (feel free to PR the workaround if you want)
