### ISSUE TITLE
Thanks to TimeSquare

### ISSUE THREAD

**Issue by BKChandan** [square/android-times-square#255]
HI,

Thanks to TimeSquare. I was able to achieve this. If any one is looking at something like this, please mail me on chandan.bk@avanseus.com

I can help them.

![screenshot_2016-01-05-15-36-45](https://cloud.githubusercontent.com/assets/16475324/12112443/94a4acf8-b3c2-11e5-9e19-d2ab41f61b1b.png)

**Comment by JakeWharton** [comment]
Looks great! Thanks.

**Comment by imabhishek** [comment]
Yes i need something similar to this could you please help me

**Comment by JaydipRadadiya** [comment]
Hi @BKChandan 

Exactly I need same as can you help me, please!

Thank you for your wonderful achievement well done!
