### ISSUE TITLE
Bug in CalendarCellDecorator

### ISSUE THREAD

**Issue by darxmorph** [square/android-times-square#261]
Okay so here is my code:

```
CalendarPickerView mycalendar = (CalendarPickerView) findViewById(R.id.mycalendar);

int calendarMonths = 24;
Calendar max = Calendar.getInstance();
max.add(Calendar.MONTH, calendarMonths - 1);
max.set(Calendar.DATE, max.getActualMaximum(Calendar.DATE));

Calendar min = Calendar.getInstance();
min.set(Calendar.DATE, min.getActualMinimum(Calendar.DATE));
mycalendar.init(min.getTime(), max.getTime());

DateFormat mydateformat = new SimpleDateFormat("dd/MM/yyyy");

List<CalendarCellDecorator> decoratorList = new ArrayList<>();
try {
    decoratorList.add(new EventDecorator(mydateformat.parse("24/02/2016"), Color.BLACK));
} catch (Exception e) {
    e.printStackTrace();
}

// Decorator code
mycalendar.setDecorators(decoratorList);

public class EventDecorator implements CalendarCellDecorator {
    private Date evd;
    private int BackgroundColor;
    public EventDecorator (Date evd, int BackgroundColor) {
        this.evd = evd;
        this.BackgroundColor = BackgroundColor;
    }

    @Override
    public void decorate(CalendarCellView calendarCellView, Date date) {
        if (date.equals(evd)) {
            calendarCellView.setBackgroundColor(BackgroundColor);
        }
    }
}
```

XML:

```
<com.squareup.timessquare.CalendarPickerView
    android:id="@+id/mycalendar"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```

Every 3 months the cell at the same position will also be colored.

times-square version: 1.6.5

This will result in something like this:
![screenshot](https://cloud.githubusercontent.com/assets/13508882/13199149/a7ce04c6-d81d-11e5-9358-caa123ed9067.png)

**Comment by edenman** [comment]
The problem is that your code never un-sets the special background:
```    
        if (date.equals(evd)) {
            calendarCellView.setBackgroundColor(BackgroundColor);
        }
```
You'll need to add an `else` block that does a `calendarCellView.setBackgroundResource(R.drawable.calendar_bg_selector)`

**Comment by akmalshukri** [comment]
i have same issue .. but when it put 
if (date.equals(evd)) {
            calendarCellView.getDayOfMonthTextView().setCompoundDrawablesWithIntrinsicBounds(0,0,icon,0);
        }
else { 
calendarCellView.getDayOfMonthTextView().setCompoundDrawablesWithIntrinsicBounds(0,0,0,0);
}

date after first date , all dont have the icon .. 
let say have 3 date , 20-11-2017,27-11-2017 and 29-11-2017 .. These two date 27-11-2017 and 29-11-2017 dont have icon.
