### ISSUE TITLE
Date difference in Arabic Calender

### ISSUE THREAD

**Issue by SoaringColorado** [square/android-times-square#262]
I am facing a problem in case of Arabic.The calender shows the current date two days ahead. Example, if today is 24th Feb Wednesday then in Arabic it is showing 24th Feb Friday. How can this is solved?

**Comment by edenman** [comment]
@SoaringColorado not sure...can you attach the code snippet where you're initializing the `CalendarPickerView`?

**Comment by edenman** [comment]
@SoaringColorado closing.  Re-open if you're still having issues.
