### ISSUE TITLE
Unable to extend range

### ISSUE THREAD

**Issue by girdharpatel** [square/android-times-square#263]
Hi Team,

Can you please/enhance library to have below thing?

For RANGE selection type,  say I have selected my range as 5 to 12. I want to do below.
1. Want to extend my RANGE till say date 15 (new RANGE 5 to 15). Currently once range is selected and if I select any new date, its clearing the existing range but instead it should actually extend last date to 15 and new range should become 5 to 15.

2. Want to reduce my RANGE. Say my current selected range is 5 to 15 and want to reduce last date of range to 12. I should be able to tap on 12 and it should update range selection as 5 to 12.

**Comment by edenman** [comment]
Because there are people out there using RANGE mode as it's currently designed, I think we should leave it like it is. Feel free to fork and change the logic in doSelectDate. Sorry!
