### ISSUE TITLE
How to set a second minimum date

### ISSUE THREAD

**Issue by omuradil** [square/android-times-square#264]
i have two Buttons. First - Depart and second - Arrive.  At the date of departure minDate = today. And the arrival date minDate should be equal to the selected date of departure. **how to put minDate?**

**Comment by edenman** [comment]
You can either use `inMode(SelectionMode.RANGE)`.  Or if you don't want intermediate dates to show as selected, `setDateSelectableFilter` with your own custom logic based on existing selected date.
