### ISSUE TITLE
CalendarPickerView doesn't fill space correctly after screen rotation on an N device

### ISSUE THREAD

**Issue by OnciZL** [square/android-times-square#265]

**Comment by aaronhe42** [comment]
I am gonna translate this. Basically, @OnciZL was saying when using the widget in dialog, `CalendarPickerView`'s `onMeasure` does wrong calculation after screen orientation changes on Android N.

See screenshots.

![screenshot_20160311-201803](https://cloud.githubusercontent.com/assets/641157/13720767/7c1921b8-e7c6-11e5-8b78-6402c01ebad2.png)
![screenshot_20160311-201701](https://cloud.githubusercontent.com/assets/641157/13720769/7f23082e-e7c6-11e5-8d47-c3b634941c0c.png)

**Comment by edenman** [comment]
Thanks @aaronhe42!  I did a quick google translate but I don't have an N device handy so wasn't able to repro.  If somebody wants to submit a PR for this I'm happy to review.  Will probably take me a week or two to look into it properly myself.
