### ISSUE TITLE
Unable to set different color for first and last date of the range

### ISSUE THREAD

**Issue by girdharpatel** [square/android-times-square#270]
Hi,

I have requirement where I want to set different text color for the first and last date of the range. Is it possible to do this? Let me know if I can customize this anywhere in code.

For e.g., My range is from April 10th to 15th. Text color of date 10th and 15th should be in White color where as all other dates on calendar in black.

**Comment by edenman** [comment]
You can implement a CalendarCellDecorator or if you need even more control, DayViewAdapter.
