### ISSUE TITLE
Select range with drag

### ISSUE THREAD

**Issue by Ajtak** [square/android-times-square#272]
Hi.
It's possible select range with touch? I need click and touch to display with drag. I will one date and touch down and and go to end range on display.

**Comment by edenman** [comment]
This is not currently supported.  In theory it's possible if you set a touch listener on the CalendarPickerView and then call `selectDate(foo, false)` when you detect that the drag events are over another cell.  It doesn't immediately sound like something we'd want to support out of the box, but if you get it working, feel free to send a PR and we can talk about it.

**Comment by Ajtak** [comment]
I tried set touch listener for calendar, but not working correctly. :(

**Comment by LeHieu97** [comment]
@Ajtak Did you make it work for now? I really need this :(
