### ISSUE TITLE
cell.setHighlighted(boolean) and CalanderPickerView.highlightDates(Collection<Date>) are not working

### ISSUE THREAD

**Issue by rosamerinoclaros** [square/android-times-square#273]
I am using the CalendarPickerView in SelectionMode range. If the selected range contains weekends cells, these won't get hightlighted. I need to highlight the whole selected range, weekends included. 
I tried both ways:
1. In my overwritten CalendarCellDecorator class, decorate(CalendarCellView cell, Date date) using cell.setHighlighted(true)
2. After I have both startDate and endDate, iterate all days, find the weekends and call CalanderPickerView.highlightDates(Collection<Date>)

But none of this worked out. I tried to hightlight programmatically any cell: no success.

**Comment by edenman** [comment]
The range mode in the sample app seems to select weekend days just fine: 
![device-2016-04-07-082717](https://cloud.githubusercontent.com/assets/1063557/14356646/9850b5f6-fc9a-11e5-9eff-9be5b52f0cf7.png)
So maybe just something wrong in your initialization?  Re-open if you still think there's a bug.

**Comment by rosamerinoclaros** [comment]
Then it should be because I am using a custom CalendarCellDecorator, where I define which cells are selectable. But anyway, try the method cell.setHighlighted(true), for me it does not work.

**Comment by edenman** [comment]
@rosamerinoclaros can you post the code for your CalendarCellDecorator?

**Comment by rosamerinoclaros** [comment]
Yes, of course.

```
public class SelectableDecorator implements CalendarCellDecorator {

        @Override
        public void decorate(CalendarCellView cell, Date date) {
            if(isDefaultCalendar){
                if(isWeekend(date)){
                    cell.setSelectable(false);
                }
            } else {
                if (mRentalStartDate != null && mRentalEndDate != null) {
                    if(date.after(mRentalStartDate)&&date.before(mRentalEndDate)){
                        //TODO: fix weekend cells not highlighted on selection range
                    }
                } else {
                    if(isSelectable(date)){
                        cell.setSelectable(true);
                    }
                }
            }
        }
    }
```

**Comment by rosamerinoclaros** [comment]
One remark: everytime onDateSelected is called, I reset the Decorator. The reason for this is that I need different selectability rules for start and enddates.
