### ISSUE TITLE
scrollToSelectedMonth not working?

### ISSUE THREAD

**Issue by LebetsVI** [square/android-times-square#275]
Hi!
How to scrool to date if function scrollToSelectedMonth not working?

`private void scrollToSelectedMonth(final int selectedIndex, final boolean smoothScroll) {
    post(new Runnable() {
      @Override public void run() {
        Logr.d("Scrolling to position %d", selectedIndex);

        if (smoothScroll) {
          //smoothScrollToPosition(selectedIndex);
        } else {
          //setSelection(selectedIndex);
        }
      }
    });
  }`

2 calls are commented (smoothScrollToPosition, setSelection). If uncomment its not realisation of that fuctions.

This function calls from 
public boolean scrollToDate(Date date);

I use like this:
`
Date ddd;
...
final CalendarPickerView calendar = (CalendarPickerView) calView.findViewById(R.id.calendar_view);

calendar.init(lastYear.getTime(), nextYear.getTime())
                .inMode(CalendarPickerView.SelectionMode.SINGLE)
                .withSelectedDate(ddd);`

but calendar show "nextYear" date;

**Comment by pantrif** [comment]
You can use calendar.scrollToDate(new Date());

**Comment by LebetsVI** [comment]
Thanks fo reply.

Sorry, but "scrollToDate" calls the  "scrollToSelectedMonth(final int selectedIndex)" and further calls the scrollToSelectedMonth(final int selectedIndex, final boolean smoothScroll).

and... we came back to 

`private void scrollToSelectedMonth(final int selectedIndex, final boolean smoothScroll) {
    post(new Runnable() {
      @Override public void run() {
        Logr.d("Scrolling to position %d", selectedIndex);

        if (smoothScroll) {
          //smoothScrollToPosition(selectedIndex);
        } else {
          //setSelection(selectedIndex);
        }
      }
    });
  }`
  
It turns out that the function does not work.

**Comment by pantrif** [comment]
I cannot understand why this is not working for you and why you have put in comments these methods.  I use scrollToDate to a project of mine and it works perfectly fine. 
I suggest you to try the original unmodified code to see if you can make it work.

**Comment by LebetsVI** [comment]
Sorry, Leonidas.
I got a code from another programmer and he used custom version of You library where CalendarPickerView class extends from ViewPager.
Now I see last release of You code and saw that class extends from ListView and all my aqestions are resolved.
Once again, I apologize that confuse you.
Best regards and thanks for library!
