### ISSUE TITLE
Add support to JODA-TIME

### ISSUE THREAD

**Issue by jcmartins** [square/android-times-square#277]
Please add support to
http://www.joda.org/joda-time/

**A selection of key features:**
LocalDate - date without time
LocalTime - time without date
Instant - an instantaneous point on the time-line
DateTime - full date and time with time-zone
DateTimeZone - a better time-zone
Duration and Period - amounts of time
Interval - the time between two instants
A comprehensive and flexible formatter-parser

**Comment by JakeWharton** [comment]
There's no good way to support this optionally. I would recommend you fork the project and a make a joda-specific variant. If we were to use an alternate date/time library it would be the JSR310 backport which supersedes jodatime.
