### ISSUE TITLE
It should have some way to set custom day view adapter for particular date/dates.

### ISSUE THREAD

**Issue by imabhishek** [square/android-times-square#280]
I have used your custom calendar example but it shows the custom view for all the dates in the date range, but it want this custom cell day view on some selected date please help me....

```
public class SampleDayViewAdapter implements DayViewAdapter
{
 @Override
  public void makeCellView(CalendarCellView parent) {
      View layout =      LayoutInflater.from(parent.getContext()).inflate(R.layout.closed_date_calendar_day_view, null);
      parent.addView(layout);
      parent.setDayOfMonthTextView((TextView) layout.findViewById(R.id.day_view));
  }
}
```

**Comment by edenman** [comment]
If I understand your question correctly: your DayViewAdapter should create the custom views and then you should use a CalendarCellDecorator to toggle on/off some part of the custom view based on the date or whatever other criteria you need.

**Comment by imabhishek** [comment]
I could not find what you are saying could you please give me some sample code

**Comment by imabhishek** [comment]
Thank you soo muchhh @edenman , I got the ansswer.... :)

**Comment by imabhishek** [comment]
@edenman when i scroll the calendar custom cell decorator automatically applies to all the months...

**Comment by pedrofsn** [comment]
@imabhishek did you fixed? I want to do the same.

**Comment by imabhishek** [comment]
@pedrofsn which one  scrolling issue ? 
this issue  yet to be fixed :(

**Comment by poojagaonkar** [comment]
@imabhishek Could you share how you implemented setting the adapter to certain date?

**Comment by Mohamdaoui** [comment]
@poojagaonkar, I believe @edenman already answered, you just go to the decorate method in the SampleDecorator and you have there the date passed as a parameter to the decorate method, so test on the date, and you can do your customization based on that.
