### ISSUE TITLE
Selected Date view

### ISSUE THREAD

**Issue by omiu** [square/android-times-square#281]
How can i modify the background and text color in a selected View cell? can i do it from xml?

**Comment by imabhishek** [comment]
You can change text color here in @color/custom_calendar_text_selector.xml file
at  ```
<item app:tsquare_state_today="true" android:color="@color/custom_text_selected"/>
    <item app:tsquare_state_selectable="false" android:color="@color/custom_text_inactive" />
```

and for background you can create your own selectors and add in @drawable/calendor_bg_selector.xml

```
<?xml version="1.0" encoding="utf-8"?>

<selector xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:app="http://schemas.android.com/apk/res-auto">
    <item android:state_selected="true" android:drawable="@drawable/bg_circle_selected"/>
    <item android:state_pressed="true" android:drawable="@drawable/bg_circle_selected"/>
    <item app:tsquare_state_current_month="false">
        <shape android:shape="rectangle">
            <solid android:color="@color/white"/>
        </shape>
    </item>
    <item app:tsquare_state_today="true" android:drawable="@drawable/bg_circle_today"/>
    <item>
        <shape android:shape="rectangle">
            <solid android:color="@color/white"/>
        </shape>
    </item>
</selector>
```
