### ISSUE TITLE
Cant auto or manual scroll to 'today' when using in a fragment

### ISSUE THREAD

**Issue by icyicarus** [square/android-times-square#283]
when i use time square in an activity it can automatically scroll to my 'selected date', but when i put that in a fragment, using exactly the same code, it just start with the 'minDate' date, i wonder why.
Fragment code: 
![qq 20160515120135](https://cloud.githubusercontent.com/assets/11155311/15271957/d699d3f2-1a94-11e6-95d6-a7da6d3d3028.png)
and it seemed like this, i just swiped from left fragment to calender fragment, and it started from 'minDate'
![screenshot](https://cloud.githubusercontent.com/assets/11155311/15271942/0885903c-1a94-11e6-8d07-36a458c61798.png)

sorry for not pasting my code up here, im not quite familiar with this editor and when i paste my code here it seems weird, i will paste them below in the reply

**Comment by icyicarus** [comment]
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View root = inflater.inflate(R.layout.fragment_calender, container, false);
        Calendar nextYear = Calendar.getInstance();
        nextYear.add(Calendar.YEAR, 1);

        Calendar lastYear = Calendar.getInstance();
        lastYear.add(Calendar.YEAR, -1);

        calendar = (CalendarPickerView) root.findViewById(R.id.mainCalenderView);
        calendar.init(lastYear.getTime(), nextYear.getTime()) //
                .inMode(CalendarPickerView.SelectionMode.SINGLE) //
                .withSelectedDate(new Date());
        calendar.setOnDateSelectedListener(new CalendarPickerView.OnDateSelectedListener() {
            @Override
            public void onDateSelected(Date date) {
                Intent i = new Intent(getContext(), OverView.class);
                i.putExtra("noteDate", calendar.getSelectedDate().getTime());
                startActivity(i);
            }

            @Override
            public void onDateUnselected(Date date) {
            }
        });
        return root;
    }

**Comment by edenman** [comment]
Yeah I have no idea.  Closing since this is v old.
