### ISSUE TITLE
Change first day of week to Monday

### ISSUE THREAD

**Issue by winniseptiani** [square/android-times-square#285]
Hi,
How to set CalendarPickerView to start first day of week to Monday instead of Sunday? I could't find any method in builder to set the first day of week and i could't find any sample also. Thanks a lot for your help

**Comment by edenman** [comment]
This is currently done based on the user's Locale.  See https://github.com/square/android-times-square/blob/master/library/src/test/java/com/squareup/timessquare/CalendarPickerViewTest.java#L575 for a test that shows this working for the British.

**Comment by eslamwael74** [comment]
this is inversed cell day of weeks and start in monday and date wrong!!
