### ISSUE TITLE
年份和星期怎么变成中文的啊？

### ISSUE THREAD

**Issue by gitzgq** [square/android-times-square#287]
我现在compile 'com.squareup:android-times-square:1.6.5@aar'   用这种方式  运行出来的年份和星期是英文的，怎么变成中文的？  麻烦解决告知一下！谢谢

**Comment by aaronhe42** [comment]
Let me translate this first. So @gitzgq was asking why the text for year/week is in English? Is there a way to show the text in Chinese?

**Comment by aaronhe42** [comment]
I guess it's because the locale/language was set to English on your phone.

**Comment by PyBird** [comment]
I think so, too
