### ISSUE TITLE
Multiple Range dates

### ISSUE THREAD

**Issue by winniseptiani** [square/android-times-square#291]
Hi,
Is it possible to create multiple range dates? My purpose is to display multiple activity schedules from certain date to certain date in my calendar. I tried to modify the "multi" menu in sample code, like snippet below, but it produced an exception "java.lang.IllegalArgumentException: RANGE mode only allows two selectedDates.  You tried to pass 6".

        multi.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                setButtonsEnabled(multi);

                calendar.setCustomDayView(new DefaultDayViewAdapter());
                Calendar today = Calendar.getInstance();
                ArrayList<Date> dates = new ArrayList<Date>();
                for (int i = 0; i < 6; i++) {
                    today.add(Calendar.DAY_OF_MONTH, 3);
                    dates.add(today.getTime());
                }
                calendar.setDecorators(Collections.<CalendarCellDecorator>emptyList());
                calendar.init(new Date(), nextYear.getTime()) //
                    .inMode(SelectionMode.MULTIPLE) //
                    .inMode(SelectionMode.RANGE)
                    .withSelectedDates(dates);
            }
        });

I apologise if my English is bad. Thank for your help.

**Comment by edenman** [comment]
there is no "multiple ranges" functionality currently.  i don't think it's a common enough usecase for us to support here, but feel free to fork!
