### ISSUE TITLE
Set different background for different dates

### ISSUE THREAD

**Issue by MadhuriHR** [square/android-times-square#295]
I want to set background of few dates with different colors as shown in the attachment. How can I do this ? Also, how to remove the disabled dates?
![screenshot_2016-07-14-17-40-51](https://cloud.githubusercontent.com/assets/20457708/16908199/63199b62-4ce7-11e6-892d-73ed345b6b6c.png)

**Comment by akmalshukri** [comment]
@MadhuriHR you solve this ?

**Comment by edenman** [comment]
You can implement a CalendarCellDecorator or if you need even more control, DayViewAdapter.

**Comment by akmalshukri** [comment]
Now, i can change calendarViewCell background .. but how to show maybe just bullet or line or indicator only for that date ? something like this image ..

**Comment by edenman** [comment]
again, use a `DayViewAdapter`

**Comment by akmalshukri** [comment]
Alright @edenman  .. now already can .. thanks you ... Last question is every time i scroll in calendar look like it will run this setDecorators , how to avoid it ?
