### ISSUE TITLE
Add option to provide list of dates instead of range in init()

### ISSUE THREAD

**Issue by balasankarc** [square/android-times-square#296]
Hi,

Is it possible to enable selection on specific dates alone. For example, I am creating a hotel booking app and the hotel is open on certain arbitrary dates only. I want a user to be able to select one of these arbitrary dates. How to do that?

From what I understood, the init function takes a range of dates, not a list of specific dates. Am I wrong?

**Comment by PyBird** [comment]
Oh, I'm sorry. I don't know, either.

**Comment by AngelOfMors** [comment]
CalendarPickerView calendar = (CalendarPickerView) rootView.findViewById(R.id.calendar_view);
			Calendar nextDay = Calendar.getInstance();
			final ArrayList<Date> dates = new ArrayList<>();
			dates.add(new Date(2016 - 1900, 9, 27));
			dates.add(new Date(2016 - 1900, 9, 29));
			dates.add(new Date(2016 - 1900, 10, 1));
			dates.add(new Date(2016 - 1900, 10, 4));
			Date dMin = Collections.min(dates);
			Date dMax = Collections.max(dates);
			nextDay.setTime(dMax);
			nextDay.add(Calendar.DATE, 1);
			calendar.init(dMin, nextDay.getTime());
			calendar.selectDate(dMin, true);
			calendar.highlightDates(dates);
			calendar.setDateSelectableFilter(new CalendarPickerView.DateSelectableFilter() {
				@Override
				public boolean isDateSelectable(Date date)
				{
					return dates.indexOf(date) >= 0;
				}
			});
