### ISSUE TITLE
Hightlight different dates with different colors

### ISSUE THREAD

**Issue by poojagaonkar** [square/android-times-square#297]
Hello,

I want to show  2 sets of dates with two different colors. Currently, I am able to achieve highlighting of only one set of dates with one color by specifying `<color name="calendar_highlighted_day_bg">YOUR_COLOR</color> ` in my colors.xml. How can I specify another color for the other set of dates?
![untitled](https://cloud.githubusercontent.com/assets/7856684/17512108/e77c657a-5e43-11e6-8f6a-ec6b9d490f05.png)

**Comment by edenman** [comment]
You can implement a CalendarCellDecorator or if you need even more control, DayViewAdapter.

**Comment by poojagaonkar** [comment]
Hi,

Thank you for the reply. It would be great if you could share a sample or
an example on how this can be achieved.

Regards,
Pooja

**Comment by poojagaonkar** [comment]
Hi Eric,

I managed to use to the CellDecorator. I am using the library for Xamarin.
But there is a slight problem when I use the cell decorator like below :-

 public void Decorate(CalendarCellView cellView, Java.Util.Date date)
        {

            var millis = date.Time;
            var dateTime = FromUnixTime(millis);
            var mDate = dateTime.Date;
            if (eventList.Contains(mDate))
            {


cellView.SetBackgroundColor(Android.Graphics.Color.PaleVioletRed);
            }

        }

The issue is that the Cells next to the actual dates I want to highlight
get highlighted instead of the actual ones. eg: if my date is 2016/08/05
the date 2016/08/06 get highlighted.

Can you please help me with the issue?

Thanks,
Pooja

**Comment by poojagaonkar** [comment]
Hello,

I tried using CellDecorator but wrong dates are getting decorated. Can you help me with implementing the DayViewAdapter only for certain dates?
