### ISSUE TITLE
Don't work Locale

### ISSUE THREAD

**Issue by AngelOfMors** [square/android-times-square#306]
For Russian is show English message

**Comment by edenman** [comment]
Please include the code you're using to initialize the CalendarPickerView.  And a screenshot of the resulting calendar.

**Comment by AngelOfMors** [comment]
`		@Override
		public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
		{
			View rootView = inflater.inflate(R.layout.fragment_main, container, false);
			CalendarPickerView calendar = (CalendarPickerView) rootView.findViewById(R.id.calendar_view);
			Calendar nextDay = Calendar.getInstance();
			final ArrayList<Date> dates = new ArrayList<>();
			dates.add(new Date(2016 - 1900, 9, 27));
			dates.add(new Date(2016 - 1900, 9, 29));
			dates.add(new Date(2016 - 1900, 10, 1));
			dates.add(new Date(2016 - 1900, 10, 4));
			Date dMin = Collections.min(dates);
			Date dMax = Collections.max(dates);
			nextDay.setTime(dMax);
			nextDay.add(Calendar.DATE, 1);
			calendar.init(dMin, nextDay.getTime());
			//calendar.setOnInvalidDateSelectedListener(null);
			calendar.selectDate(dMin, true);
			calendar.highlightDates(dates);
			calendar.setDateSelectableFilter(new CalendarPickerView.DateSelectableFilter() {
				@Override
				public boolean isDateSelectable(Date date)
				{
					return dates.indexOf(date) >= 0;
				}
			});
			return rootView;
		}
`
![screenshot_1477550650](https://cloud.githubusercontent.com/assets/13793037/19757197/6e0e67f4-9c43-11e6-8452-8adc325dcc25.png)

**Comment by edenman** [comment]
Russian support was just added in 1.7.0
