### ISSUE TITLE
limit range selection to certain amount of days

### ISSUE THREAD

**Issue by kevin-808** [square/android-times-square#309]
Hi
I was wondering if its possible to limit the number selected days in RANGE mode?

**Comment by NahomAgidew** [comment]
@edenman Should I do this? I don't want to waste my time if this feature isn't needed.

**Comment by NahomAgidew** [comment]
@edenman Is this feature needed?

**Comment by shamilirani** [comment]
Yes I too need that feature

**Comment by NahomAgidew** [comment]
@kevin-808 @shamilirani Done!

**Comment by edenman** [comment]
@NahomAgidew @kevin-808 @shamilirani sorry, I just saw this.  I'm pretty sure there's no need for a new feature here: you can accomplish this by having a custom `OnDateSelectedListener` that checks `getSelectedDates()` and if it's over the max your app wants to allow, reverts the selection by re-calling `init` with the previously selected dates in `withSelectedDates`.  

I'll admit this is a bit janky, having to re-init.  @NahomAgidew if you'd like to make a contribution here, I'd accept a `selectDates(Collection<Date>)` method (similar to `selectDate`).

**Comment by NahomAgidew** [comment]
@edenman but why go through all that?

**Comment by edenman** [comment]
@NahomAgidew because this is a pretty fringe usecase and i don't want to further complicate the main codepath.
