### ISSUE TITLE
Month views divider

### ISSUE THREAD

**Issue by zvonkec** [square/android-times-square#313]
I am trying to divide month views in CalendarPickerView by using custom color.

I have tried following :

`CalendarPickerView calendarPickerView = (CalendarPickerView) view.findViewById(R.id.calendar_view);
calendarPickerView.setDividerHeight(50);
calendarPickerView.setDivider(ContextCompat.getDrawable(getActivity(),R.color.white_background)); `

Althought month views are divided correctly considering distance, there is no selected color visible beetwen them. It looks like I just added padding to every month view. How could I actually divide these views?

**Comment by edenman** [comment]
there's nothing android-times-square specific here, afaict.  not sure why it's not working, but http://stackoverflow.com/a/11254409/214240 seems to indicate you have to set the height after the color.
