### ISSUE TITLE
Unselect date on button click

### ISSUE THREAD

**Issue by captswag** [square/android-times-square#315]
Is there a way to unselect the dates on the CalendarPickerView? I feel like this will be a must wanted feature. 
*I'm using SelectionMode.RANGE*, and in my scenario the date range should not exceed 6 months. So when I select start date and end date, if the range between them exceeds 6 months, then in the onDateSelected() callback, I should show Toast message, followed by unselecting the selected dates.
So I guess this would be a feature other developers will also be looking out for. Thanks in advance.

**Comment by edenman** [comment]
way late on this one, sorry. `clearSelectedDates` is what you want.
