### ISSUE TITLE
Sample decorator class issue

### ISSUE THREAD

**Issue by bhadkiaftab** [square/android-times-square#319]
I use sample decorator class to saw the rate on each date.but whenever i m selection the data everytime all the cell are created and update so while selection multiple date its not responding at all.ANR alert is coming.

**Comment by edenman** [comment]
@bhadkiaftab sorry, catching up on backlog in this project.  it's been a long time so i'm going to just close this.  if you want to submit a sample project that shows the issue, i'll take a look.
