### ISSUE TITLE
Using CalendarPickerView inside BottomSheetDialogFragment

### ISSUE THREAD

**Issue by MerveGencer** [square/android-times-square#322]
If you use CalendarPickerView inside a fragment that extends BottomSheetDialogFragment, the scrolling behavior is not behaves as expected. Scrolling down is just fine, but if you scroll up, it closes the dialog fragment instead of scrolling up to the upper list items. This might be the problem of BottomSheetDialogFragment (I tested with other ListViews, it is), but i guess it is best for the CalendarPickerView to extend RecyclerView instead of ListView. BottomSheetDialogFragments work well with RecyclerViews.

**Comment by joseph-acc** [comment]
Use mCalender.setNestedScrollingEnabled(true)
