### ISSUE TITLE
How to Convert Date and create event in splanner or system calendar ?

### ISSUE THREAD

**Issue by deshario** [square/android-times-square#332]
Hi Bro! How to Convert Date and create event in splanner or system calendar by the selected date?
![capture](https://cloud.githubusercontent.com/assets/11426727/22338061/05008c1a-e419-11e6-8343-6a330231a10b.PNG)

**Comment by DarkSpam91** [comment]
calendar.setOnDateSelectedListener(new CalendarPickerView.OnDateSelectedListener() {

            @Override
            public void onDateSelected(final Date date) {
Calendar c = Calendar.getInstance();
                c.setTime(date);
                int dayOfWeek = c.get(Calendar.DAY_OF_MONTH);
                int Month = c.get(Calendar.MONTH)+1;
                int Year = c.get(Calendar.YEAR);
                int LastDayonMonth = c.getActualMaximum(Calendar.DAY_OF_MONTH);
                switch (Month){

case 1:
break;
....
case 13:
break;
}
}
So you can get the selected date and the month too
