### ISSUE TITLE
[question] Can't change layout params of custom cell view dynamically

### ISSUE THREAD

**Issue by m-glebova** [square/android-times-square#334]
[question] Hi, thank you for the amaizing library. Please help me with my issue. I should animate clicking on the calendar cell (increase the oval height and width), but my code working in other views (for example, ListView) doesn't work in the calendar. Here is the code for custom adapter:
public class SampleDayViewAdapter implements DayViewAdapter {
  @Override
  public void makeCellView(CalendarCellView parent) {
      View layout = LayoutInflater.from(parent.getContext()).inflate(R.layout.day_view_custom, null);
      parent.addView(layout);
      final ImageView iv = (ImageView) layout.findViewById(R.id.iv);
      final ViewGroup vg = (ViewGroup) layout.findViewById(R.id.container);
      iv.setOnClickListener(new View.OnClickListener() {
          @Override
          public void onClick(View v) {
              Toast.makeText(v.getContext(), "Click!", Toast.LENGTH_SHORT).show();
              TransitionManager.beginDelayedTransition(vg);
              ViewGroup.LayoutParams params = iv.getLayoutParams();
              params.width = 100;
              params.height = 100;
              iv.setLayoutParams(params);
          }
      });
      parent.setDayOfMonthTextView((TextView) layout.findViewById(R.id.day_view));
  }
}

**Comment by edenman** [comment]
Yeah sorry, for custom code you're on your own.
