### ISSUE TITLE
Show one month

### ISSUE THREAD

**Issue by Mohamdaoui** [square/android-times-square#337]
Hello,
Thank you for this amazing custom calendar.

I would like to be able to show one month with a scroll left/right just like the regular CalendarView, is that possible at all with thie lib ?

Thanks and regards.
Mohamed.

**Comment by BoxResin** [comment]
I'm looking for that feature too.

**Comment by Mohamdaoui** [comment]
I think I will just do it manually, by setting the start date and end date each time, add controllers and modify those dates accordingly.

**Comment by edenman** [comment]
Yup, that's currently the only supported way to have horizontal scrolling.
