### ISSUE TITLE
How to deselect a date in Multi mode after user clicks on it ?

### ISSUE THREAD

**Issue by passiondroid** [square/android-times-square#342]
How to deselect a date in Multi mode after user clicks on it. 
I want to navigate the user to next screen when user selects a date but i dont want that date to get highlighted. When user comes back to the calendar view that date shows selected instead it should show unselected.

**Comment by edenman** [comment]
Try hooking up a `OnDateSelectedListener` and calling `selectDate` to unselect the date.
