### ISSUE TITLE
Can't open on button Click

### ISSUE THREAD

**Issue by swanandvaidya** [square/android-times-square#344]
I am unable to open this library on a button click.
I am getting error as follows:
java.lang.IllegalStateException: Must have at least one month to display.  Did you forget to call init()
Please let me know what is wrong with this?

**Comment by BoxResin** [comment]
You have to call 'init()' method before you use it.

2017년 3월 3일 (금) 오후 7:51, Swanand Vaidya <notifications@github.com>님이 작성:
