### ISSUE TITLE
Calendar is taking time to open on button click.

### ISSUE THREAD

**Issue by swanandvaidya** [square/android-times-square#345]
I have a simple button and I am opening Calendar view on it, but to open its taking time to display? Any solution for this?

**Comment by idrisbohra** [comment]
Hi @swanandvaidya, i am facing the same issue as yours. Did you find any solution? Please let me know. Thank you.

**Comment by edenman** [comment]
The current algorithm is slow if you are trying to select from a large number of months.  This is unfortunate but we have no plans to change this atm.
