### ISSUE TITLE
How to override CalendarCell.DayHeader

### ISSUE THREAD

**Issue by deandalm** [square/android-times-square#349]
Is there a way to override CalendarCell.DayHeader style?  Or is there another way to change the attributes of the TextViews in the header similar to what DayViewAdapter exposes?

**Comment by edenman** [comment]
If you want to change the text color, add
```
      app:tsquare_headerTextColor="#FF0000"
```
If you want to change the text size or some other attribute, just create a style with the same name and add attributes there:
```
  <style name="CalendarCell.DayHeader">
    <item name="android:textSize">40sp</item>
    <item name="android:textStyle">bold</item>
  </style>
```
