### ISSUE TITLE
different backgrounds for start date and end date

### ISSUE THREAD

**Issue by rajeshandroid** [square/android-times-square#353]
Please provide me the solution to change the background of start date and end date with different images

**Comment by edenman** [comment]
You can implement a CalendarCellDecorator or if you need even more control, DayViewAdapter.

**Comment by koocbor** [comment]
@edenman  - I know this is closed but there is an issue trying to get the RangeState of the CalendarCellView to determine if a cell is a start / end of the range.  getRangeState() is public but the MonthCellDescriptor class isn't accessible so the RangeState enum isn't available.

You can use the .ordinal() property but it feels dirty.

**Comment by edenman** [comment]
Ah, bummer.  @koocbor if you want to submit a PR that moves RangeState to the top-level and makes it public, I'll accept that.

**Comment by RushiMThakker** [comment]
@koocbor How did you use ordinal? I tried with customized in sample but it applies that customization to complete range of selected dates. Please help

**Comment by koocbor** [comment]
@RushiMThakker - Here is how I used the ordinal to decorate calendar cells:

```java
class AppCalendarDecorator implements CalendarCellDecorator {

    @Override
    public void decorate(CalendarCellView cellView, Date date) {

        RangeState rangeState = cellView.getRangeState();

        switch (rangeState) {
            case RangeState.NONE:

                if (cellView.isSelected()) {
                    cellView.setBackgroundResource(R.drawable.bg_calendar_start_date);
                } else {
                    cellView.setBackgroundResource(0);
                }
                break;

            case RangeState.FIRST:
                cellView.setBackgroundResource(R.drawable.bg_calendar_start_date);
                break;

            case RangeState.MIDDLE:
                cellView.setBackgroundResource(R.color.colorGray);
                break;

            case RangeState.LAST:
                cellView.setBackgroundResource(R.drawable.bg_calendar_end_date);
                break;

            default:
                cellView.setBackgroundResource(0);
                break;
        }
    }
}
```

To apply to the CalendarPickerView:

```java
List<CalendarCellDecorator> decoratorList = calendarView.getDecorators();
if (decoratorList == null) {
    decoratorList = new ArrayList<>();
}
decoratorList.add(new AppCalendarDecorator());
calendarView.setDecorators(decoratorList);
```

The result is below:

<img width="269" alt="screenshot 2017-07-19 06 34 40" src="https://user-images.githubusercontent.com/3985177/28362926-6154d05a-6c4c-11e7-9989-1d72eaf1415d.png">

**Comment by RushiMThakker** [comment]
@koocbor There is no such method as getRangeState in CalendarCellView.

**Comment by koocbor** [comment]
@RushiMThakker - https://github.com/square/android-times-square/blob/master/library/src/main/java/com/squareup/timessquare/CalendarCellView.java - starting line 96 ?  It should be there and be public.

**Comment by RushiMThakker** [comment]
@koocbor  I think I downloaded direct aar with gradle dependency and it doesn't seem to be latest(1.6.5). When I downloaded zip I saw that it is at line 96. Look at this file which is part of aar. I don't know what could be the reason. So now should I put downloaded library folder in libs directly or create jar and put it. Btw, thanks a lot for your guidance.
[CalendarCellView.zip](https://github.com/square/android-times-square/files/1158879/CalendarCellView.zip)

**Comment by RushiMThakker** [comment]
@koocbor Also, as a side question do you know any library by which we can switch activities with page curl animation?

**Comment by RushiMThakker** [comment]
@koocbor Thanks a lot bro.

**Comment by koocbor** [comment]
@RushiMThakker  - the latest version is actually 1.7.3 - see here: https://mvnrepository.com/artifact/com.squareup/android-times-square

If you're using gradle for your build I would just include the reference as a dependency there:

```
dependencies {
  compile 'com.squareup:android-times-square:1.7.3@aar'
}
```

If you have to have the AAR then you can download from the link above.  Put in libs directory and include:
```
dependencies {
  compile(name:'android-times-square-1.7.3', ext: 'aar')
}
```

I can't help with the curl animation - never done that but sounds cool :)  Good luck

**Comment by RushiMThakker** [comment]
@koocbor ok. Looks like contributors of such a great library don't have time to update readme. I actually downloaded zip and created a module dependency. Do you know exact link to latest google maven central appcompat-v7. Seems like google has moved all its latest release there because its almost empty at jcenter

**Comment by JaydipRadadiya** [comment]
Hi @koocbor 

How can do that like this, need help! 

Thanks.
![screenshot_20180921-152633](https://user-images.githubusercontent.com/12029999/46016430-6a218380-c0f2-11e8-91c4-4996809b4be1.png)

**Comment by mpatel184197** [comment]
> @RushiMThakker - Here is how I used the ordinal to decorate calendar cells:
> 
> ```java
> class AppCalendarDecorator implements CalendarCellDecorator {
> 
>     @Override
>     public void decorate(CalendarCellView cellView, Date date) {
> 
>         RangeState rangeState = cellView.getRangeState();
> 
>         switch (rangeState) {
>             case NONE:
> 
>                 if (cellView.isSelected()) {
>                     cellView.setBackgroundResource(R.drawable.bg_calendar_start_date);
>                 } else {
>                     cellView.setBackgroundResource(0);
>                 }
>                 break;
> 
>             case FIRST:
>                 cellView.setBackgroundResource(R.drawable.bg_calendar_start_date);
>                 break;
> 
>             case MIDDLE:
>                 cellView.setBackgroundResource(R.color.colorGray);
>                 break;
> 
>             case LAST:
>                 cellView.setBackgroundResource(R.drawable.bg_calendar_end_date);
>                 break;
> 
>             default:
>                 cellView.setBackgroundResource(0);
>                 break;
>         }
>     }
> }
> ```
> 
> To apply to the CalendarPickerView:
> 
> ```java
> List<CalendarCellDecorator> decoratorList = calendarView.getDecorators();
> if (decoratorList == null) {
>     decoratorList = new ArrayList<>();
> }
> decoratorList.add(new AppCalendarDecorator());
> calendarView.setDecorators(decoratorList);
> ```
> 
> The result is below:
> 
> <img alt="screenshot 2017-07-19 06 34 40" width="269" src="https://user-images.githubusercontent.com/3985177/28362926-6154d05a-6c4c-11e7-9989-1d72eaf1415d.png">

what is calenderView in calendarView.setDecorators(decoratorList);
