### ISSUE TITLE
tsquare_state_current_month color text doesn't work

### ISSUE THREAD

**Issue by alextorres50** [square/android-times-square#354]
tsquare_state_current_month
doesn't work

```
<item app:tsquare_state_today="true" android:color="@color/colorblack"/>
  <item android:state_selected="true" android:color="@color/colorfonttitle"/>
  <item android:state_pressed="true" android:color="@color/colorfonttitle"/>
  <item app:tsquare_state_selectable="false" android:color="@color/colorblack" />
  <item app:tsquare_state_current_month="false" android:color="@color/colorfonttitle"/>
  <item android:color="@color/colorblack"></item>
```

but the `app:tsquare_state_current_month="false"` has the same color of of principal.

![captura](https://cloud.githubusercontent.com/assets/26494805/24430620/16c9b34c-13dd-11e7-8379-8327983a9284.PNG)

**Comment by edenman** [comment]
Check out the sample app "customized" tab.  I just tweaked the `tsquare_state_current_month` color value in `custom_calendar_text_selector.xml` and confirmed that it works.

**Comment by alextorres50** [comment]
![imagen](https://cloud.githubusercontent.com/assets/26494805/24431486/bf32e018-13e1-11e7-965c-cf16947908f7.png)

i change the value, bbut this is my result

**Comment by saurabhmdh** [comment]
Did you find the solution, I am also getting the same problem
