### ISSUE TITLE
How do I block the selection of new dates?

### ISSUE THREAD

**Issue by DarkSpam91** [square/android-times-square#357]
I need the help of the community to find a solution to block the new selection of dates when a condition is fulfilled, is it possible?

**Comment by edenman** [comment]
https://github.com/square/android-times-square/blob/master/library/src/main/java/com/squareup/timessquare/CalendarPickerView.java#L976
 or
https://github.com/square/android-times-square/blob/master/library/src/main/java/com/squareup/timessquare/CalendarPickerView.java#L994

**Comment by DarkSpam91** [comment]
thanks bro! 
Another question, is there a way to keep the dates selected even if you leave the activity?
