### ISSUE TITLE
.clearHighlightedDates() does not work on a range.

### ISSUE THREAD

**Issue by elliott-accolade** [square/android-times-square#358]
Android 6.0, using `com.squareup:android-times-square:1.6.5@aar`

1. Initialize a `CalendarPickerView` with selection type `RANGE`.
2. Set up a 'Clear' button, that when you click it, clears the calendar's selections (mCalendar.clearHighlightedDates()).
3. Run the application, select some dates (notice they are all highlighted).
4. Click your Clear button.
--> Notice that the dates are still highlighted.

Debugging shows that the `highlightedCells` in the CalendarPickerView is empty, so there is nothing to update, so the views stay highlighted. So when the dates / range are selected, shouldn't they also be added to the `highlightedCells` list?

Maybe I don't understand what the `clearHighlightedDates()` function is supposed to do.

**Comment by edenman** [comment]
Yeah, `selectedCells` != `highlightedCells`.  RANGE mode currently doesn't support a "clear selections" operation, it looks like.  If you want to add a `clearSelectedDates()` method, I'd be open to that.  Should just look something like:
```
public void clearSelectedDates() {
  clearOldSelections()
  validateAndUpdate()
}
```

**Comment by elliott-accolade** [comment]
I see - thanks for correcting me. I will try it out on my end and submit it, if it works as expected. Thanks!

**Comment by edenman** [comment]
Released in 1.7.2, should be live in maven central soon.  Thanks!

**Comment by edenman** [comment]
(fixed in #359, for posterity)

**Comment by elliott-accolade** [comment]
hey @edenman - we're planning the next sprint and I'd like to be able to close the calendar feature I'm working on. Will 1.7.2 be available in the next couple weeks? Thanks!

**Comment by edenman** [comment]
Yup, it's already out

**Comment by elliott-accolade** [comment]
I should have checked the releases tab - I was checking the Maven Repo, which only has up to 1.7.1 right now.

**Comment by edenman** [comment]
@elliott-accolade https://search.maven.org/#artifactdetails%7Ccom.squareup%7Candroid-times-square%7C1.7.2%7Caar

**Comment by elliott-accolade** [comment]
I see. This is where I was looking: https://mvnrepository.com/artifact/com.squareup/android-times-square

**Comment by JakeWharton** [comment]
Do not use that site. search.maven.org or repo1.maven.org are the real
sources of packages.

**Comment by elliott-accolade** [comment]
Got it, thanks for clarifying.
