### ISSUE TITLE
Flag to disable scrolling

### ISSUE THREAD

**Issue by WesWinn** [square/android-times-square#366]
It seems that scrolling (smooth or not) is mandatory when a user selects a date/dates. During RANGE selection, I've run into areas where I would love to disable all automatic scrolling, but I can't seem to find an option to.

Perhaps I'm missing something? Or maybe this functionality would be worth adding? I'd be happy to add it if such functionality would be an accepted PR even.

Thanks!

**Comment by edenman** [comment]
@WesWinn i don't follow.  automatic scrolling has nothing to do with `RANGE` mode.  if you want to set the selected dates and just have the view immediately jump to those dates, use `selectDate(foo, false)`

**Comment by WesWinn** [comment]
I mean for any dates, range, multiple anything. I want to select a date and have the calendar NOT scroll or reposition in any way. Right now if I click a date in the following month, it'll scroll the screen (or just move it if smooth scroll is false) and I can't seem to prevent it from doing so.

**Comment by edenman** [comment]
ah...that's not currently supported.  probably best to just fork for something like this: seems really niche.

**Comment by MasterEmit** [comment]
Would need that to. A param for selectDate would be perfect enough for me. selectDate(Date date, boolean smoothScroll, boolean scrollToSelectedMonth) or something similar. I'm not a fan of forking because I would love to stay up2date.

**Comment by raanayavarii** [comment]
Hi, 
Is there any update on this issue?
