### ISSUE TITLE
Add the feature to reset range by unselecting the start date 

### ISSUE THREAD

**Issue by cnhan21** [square/android-times-square#370]
By only setting selectable dates to be in the middle of minValue & maxValue, you may miss the situation where disabled dates to be many ranges in between.
However, you don't need to change anything relating to the structure of the Picker. The solution is to allow user to remove start date (or reset the range immediately after picking the first date of that range, no need for second tap to mark end of range).
This can be achieved by changing this:
https://github.com/cnhan21/android-times-square/blob/master/library/src/main/java/com/squareup/timessquare/CalendarPickerView.java#L649 which is
`} else if (selectedCals.size() == 1 && newlySelectedCal.before(selectedCals.get(0))) {`
to
`} else if (selectedCals.size() == 1 && (newlySelectedCal.before(selectedCals.get(0)) || newlySelectedCal.equals(selectedCals.get(0)))) {`

**Comment by edenman** [comment]
@cnhan21 what do you mean by "By only setting selectable dates to be in the middle of minValue & maxValue, you may miss the situation where disabled dates to be many ranges in between."?  Can you give me a more concrete example of what you're talking about?

**Comment by cnhan21** [comment]
What I mean is the ordinary use case is 
`calendarView.init(startDate, endDate)`
Any dates before startDate or after endDate are disabled. However in my case, when I use  `calendarView.setOnSelectableFilter(...)` it allows the calendar to have many disabled date ranges in between. For example, I want to:
- do A from Jun-5 to Jun-9
- do B from Jun-13 to Jun-17
Hence, I pick the range for work A and then (after creating a new instance of calendarView to) pick range for work B. Now the result is I have 2 disabled zones of dates in the middle. I want to make sure that any range won't overlap previously selected ranges. However, that `if` only allows user to reset by
- having a new start of range if the next picked date comes before it. E.g. pick Jun-12, picking Jun-10 will make Jun-10 the new start date of the upcoming range.
- or user has to pick a 2nd date (as end of range) after the first pick date to complete the range. Then, they'll​be able to pick the start date for a new range.
This is convenient in many cases, obviously so far, however what if we can allow user to reset the range after 1st date was picked by tapping the first date again (like in MULTIPLE mode, but I'm talking about RANGE now). That can be achieve by a minor addition to the if above.

The purpose is to also clearSelection when the 2nd picked date is the same as the 1st picked date.

Please correct me if I misunderstood anything. Kudos to you for maintaining this helpful library.

**Comment by cnhan21** [comment]
My mistake. There was already a method to do what I wanted. It's
`  public void clearSelectedDates() {`
Whenever there is an attempt to pick a forbidden range, which is a range that crosses another selected range, I can `clearSelectedDates`  and `return false` in a CellClickInterceptor.
What you guys have done is amazing! How did you foresee and cover so many use cases of the library?

**Comment by edenman** [comment]
Cool, glad to hear it!  Re: "how did you foresee and cover so many use cases" we didn't, just took feedback from the community for the last five years :)
