### ISSUE TITLE
Initial selected dates have text cut off, and artifact showing intermittently

### ISSUE THREAD

**Issue by bbil** [square/android-times-square#371]
In our usage of Times Square, we are selecting some dates when the calendar is initially created and on some devices (Nexus 5, Samsung Galaxy) we are seeing an issue. The first `n-1` days being selected have text cut off. If no selection is made when the calendar is initialized, the numbers appear correctly.

![screen shot 2017-06-26 at 6 20 45 pm](https://user-images.githubusercontent.com/2916172/27567282-bf64c696-5a9f-11e7-8d1f-79dd02417fe9.png)

(Initial selection in the above shot was 26-30)

I have been able to remedy the text cut off by selecting the initial days in a  Handler post, to delay the selection from happening immediately. This is working well enough to fix the issue, but I was wondering if there is some better explanation. The text is **not** being cut off on phones like Nexus 6p and Galaxy S8.

Also, in the above screenshot, there is a vertical line artifact between 28 and 29.
Changing the selection can fix the artifact.

![screen shot 2017-06-26 at 6 20 18 pm](https://user-images.githubusercontent.com/2916172/27567376-33a6e142-5aa0-11e7-8a1d-4244f69a3a81.png)

However it comes back **intermittently**, sometimes caused by  putting the app in the background and the bringing it to the foreground. The vertical line artifact is showing on all test devices.

![screen shot 2017-06-26 at 6 20 45 pm](https://user-images.githubusercontent.com/2916172/27567422-7763fd70-5aa0-11e7-9a28-0f4f3fbaa984.png)

## Additional Info

Using a custom DayViewAdapter to inflate a simple FrameLayout with textview.
Using a Custom Decorator to set the text color and background drawable
- based on selected vs unselected
- if on the current month
- at the beginning or end of the selection range, with some special cases at the beginning and end of the month (which version of the background to use to get the pill shape looking correct)

**Comment by wching** [comment]
Hey @bbil! We had the same behavior once, however we found out on our end that when we defined our custom adapter, the textview that we inflated wasn't not using on the **height** and **width** **match_parent**. 
Could that maybe help you out? 
Is that FrameLayout already with **match_parent**?
