### ISSUE TITLE
How to select dates in a continuous manner ?

### ISSUE THREAD

**Issue by krazykira** [square/android-times-square#372]
![screenshot_1498560762](https://user-images.githubusercontent.com/2201511/27584271-9b28feda-5b37-11e7-85f6-c107d6f0341b.png)

I want to display the selected dates between months in the similar way as AirBnb does it in a continuous order. I plan on hiding the disabled dates later. Any pointers on doing that ?

**Comment by bbil** [comment]
Could you post images of what you want? It's hard to offer pointers without a visual aid.

**Comment by krazykira** [comment]
@bbil sure here is how i want the selected dates to appear. Please notice the continuous white line which is highlighting dates. I want to implement something similar

![0-weu-d3-891640f3b77cbe88ddcaa13ef0ea539c](https://user-images.githubusercontent.com/2201511/27630732-94db1c9c-5bf6-11e7-935a-2c02fc36274c.jpg)

**Comment by bbil** [comment]
You should be able to do this with `CalendarCellDecorator`, as you can have much more granular control. You will have to use the decorator to do all of the background setting, instead of using selectors. I haven't had any luck with mixing the two concepts.
