### ISSUE TITLE
Show previous selected date in range picker

### ISSUE THREAD

**Issue by kamalahmedshaikh** [square/android-times-square#375]
Hi,
How i can show or highlight previously selected date on calendar using range picker

**Comment by bbil** [comment]
Could you upload a mock-up of what you would like to accomplish?

At a first glance, it seems like you should probably make a decorator for this. You can store whatever you want in the decorator, and use that to make decisions on what the UI should look like for a given day.

**Comment by edenman** [comment]
I _think_ this is asking for ranges to be able to go backwards (ie first you tap on July 15th and then you tap July 4th, and that creates a range from July 4-15).  This is currently not supported.  Let me know if my interpretation wasn't correct.
