### ISSUE TITLE
Make different dayselected color when single and range pick

### ISSUE THREAD

**Issue by fandyaditya** [square/android-times-square#376]
Thanks for work, this is awesome library!
Now i want  to make my calendar something like this, is it possible ?
![screenshot_20170704-183950](https://user-images.githubusercontent.com/24617294/27828817-71fec696-60e8-11e7-9c12-8ac69c84c3f1.png)
![screenshot_20170704-183955](https://user-images.githubusercontent.com/24617294/27828821-739d00d0-60e8-11e7-848c-9167aa7696a4.png)
*ss from airbnb apps

**Comment by edenman** [comment]
Yes, it is possible.  You'll have to implement a CalendarCellDecorator or if you need even more control, DayViewAdapter.
