### ISSUE TITLE
Disable a set of dates

### ISSUE THREAD

**Issue by Anoop7689** [square/android-times-square#379]
Is there a method to disable a set of dates, if no , then what is the alternative for the same , is there any native widget that can be used with android-times-square to implement the disabling functionality.

**Comment by edenman** [comment]
setDateSelectableFilter

**Comment by rakeshh025** [comment]
@edenman How to change the color of the disabled date?

**Comment by edenman** [comment]
You can implement a `CalendarCellDecorator` or if you need even more control, `DayViewAdapter`.

**Comment by rakeshh025** [comment]
@edenman Can you please provide a code snippet?
