### ISSUE TITLE
It would show wrong when I make the CalendarCellView to be View.GONE by CalendarCellView #isCurrentMonth

### ISSUE THREAD

**Issue by maohui1993** [square/android-times-square#383]
It would show wrong when I make the CalendarCellView to be View.GONE by CalendarCellView #isCurrentMonth....

### code:
`      
  List<CalendarCellDecorator> decorators = new ArrayList<>();
        CalendarCellDecorator cellDecorator = new CalendarCellDecorator() {
            @Override
            public void decorate(CalendarCellView cellView, Date date) {
                if (!cellView.isCurrentMonth()) {
                    cellView.setVisibility(View.GONE);
                }
            }
        };
        decorators.add(cellDecorator);
        calendar.setDecorators(decorators);
    }
`
### result:
![123](https://user-images.githubusercontent.com/14193060/29809904-8022ca2e-8cd0-11e7-9a4d-376e86cac6a0.png)

So, I`m hasty to resolve it by set the Text color same as the DrawableState#STATE_CURRENT_MONTH to hide it.

LOL~My English is ... bad, Sorry

**Comment by edenman** [comment]
You probably want something like `cellView.setVisibility(cellView.isCurrentMonth() ? View.VISIBLE : View.GONE); }`

**Comment by maohui1993** [comment]
year, cool, thank you~
