### ISSUE TITLE
dynamic select

### ISSUE THREAD

**Issue by eslamwael74** [square/android-times-square#387]
Hello,
 I just need to know how can i high light days which is selected for an event.
Thanks.

**Comment by edenman** [comment]
You can implement a CalendarCellDecorator or if you need even more control, DayViewAdapter.

**Comment by eslamwael74** [comment]
Example, please!!

**Comment by eslamwael74** [comment]
@edenman example please!!

**Comment by JakeWharton** [comment]
The sample has an example.
