### ISSUE TITLE
Change the gravity of month titles

### ISSUE THREAD

**Issue by gokberkerust** [square/android-times-square#389]
Hello, I need to customise gravity of month titles, but I am unable to do that with <style name="CalendarTitle"> because the gravity attribute given in xml file does not override by the attribute given in styles. Is there another way to do it?

**Comment by edenman** [comment]
Doesn't seem to be possible through any of our official APIs.  You could manually find the view and modify the gravity yourself, but that's gross.  I'd be open to a `tsquare_titleGravity` attribute if you want to submit a PR for that.

**Comment by gokberkerust** [comment]
Actually if you just delete the gravitiy attribute from month.xml then add it with style file, I would be able to override style and change the gravity. I cannot change the xml file because I simply add the library with gradle.

**Comment by edenman** [comment]
If you're not willing to fork+PR with the new feature you're requesting, I suggest just doing the hack I mentioned above: do a `findViewById(R.id.title)` and modify the gravity yourself.

**Comment by gokberkerust** [comment]
I implemented and added a pull request for it.

**Comment by edenman** [comment]
#398 should allow this
