### ISSUE TITLE
How to mark holidays and weekends unselectable with different colors?

### ISSUE THREAD

**Issue by iskuhis** [square/android-times-square#394]
I use setDateSelectableFilter for marking weekends  it shows unselectable days with gray color
I want to mention holidays unselectable as well , but with another color?

Or marking holidays as highlighted but when selecting range the highlighted days remain with their defined color ?

**Comment by edenman** [comment]
You can implement a CalendarCellDecorator or if you need even more control, DayViewAdapter.
