### ISSUE TITLE
Better Documentation.

### ISSUE THREAD

**Issue by Jam155** [square/android-times-square#395]
I feel like this library is really let down by the lack of documentation explaining it. The readme is very sparse and misses a lot of new functionality, with very little explanation of how to do things. As well as this the code isn't well commented with no method headers explaining what each of the functions does or how it is supposed to be used. Some more code examples wouldn't go amiss either.

In short

- Expand the Readme to better explain all functionality.
- Add Javadoc to all classes and functions so it is easier to read the source code
- Add more code examples explaining how to do some stuff or expand upon the currently available ones.

I've started writing up JavaDoc comments for some of the public facing functions that I am able to understand, I'll create a Pull request linking to this issue so others can expand upon it shortly.

**Comment by edenman** [comment]
I'm happy to accept targeted suggestions, but I generally lean toward making the code easy-enough to understand that you don't need javadoc.  The README could probably do with an update for some of the newer APIs though...PRs welcome!

**Comment by Jam155** [comment]
@edenman My problem is I don't think the code is lean enough to be able to understand easily. In relation to this issue it took me the better part of a day to work out how to implement colour changes for this library correctly - and I still have some issues with this. Mainly this is due to the amount of code in the library and the fact I've had to go through and read most of the classes to get a thorough understanding of the code.

For instance:

#381 #147

It's easy to say someone should be able to just read through all the code to gain a valid understanding but most people do not have the time to do this. Many people, especially new programmers, don't have the ability to do so either. Comments and documentation make this easier for people to accomplish. I know I wouldn't have spent half as long as I did trying to restyle the calendar if the code had been better commented and documented.

I can work on adding some more sections to the Readme for this too I am planning to eventually put together a code sample for styling related stuff when I get the time.

**Comment by edenman** [comment]
Yeah, I think adding a section to the README about styling would be a great addition.  My only objection is to javadoc on methods for the sake of having javadoc.
