### ISSUE TITLE
Cannot pick a date with hardware buttons (D-pad)

### ISSUE THREAD

**Issue by amdkkj** [square/android-times-square#397]
I'm testing my app using TimesSquare on an Android emulator with D-pad.

When I pressed 'down' button of D-pad on a CalendarPickerView, 
all the day cells of a month were selected although selection mode was SINGLE.

And at that time, OnDateSelectedListener.onDateSelected() was not called.

Is there a way to pick a date with D-pad?

![screenshot_1507803921](https://user-images.githubusercontent.com/10581382/31495417-86e58952-af92-11e7-980c-90afc589ae6d.png)

* TimesSquare version: 1.7.3
* Android version: 7.1.1 Nougat

**Comment by edenman** [comment]
I have no idea.  I didn't think there were any actual devices that still had a d-pad.  If you want to hook up the debugger and figure out what's going on here, I'm happy to consider a PR that fixes this :)

**Comment by amdkkj** [comment]
Okay, I'll try it.

**Comment by edenman** [comment]
Looks like your fork accomplished what you needed to?  I'm gonna close this, but lmk if you'd like to actually submit it as a PR (I think we'd want to change some of how you solved the problem)
