### ISSUE TITLE
Can not style The Selected Date Color

### ISSUE THREAD

**Issue by BbosaH** [square/android-times-square#403]
Hello . I like to use this Calender. But its selection is Blue. I want mine to be red so that it matches my theme . Is it possible ? and if so how do i do it? I cant seem to get it right. Because when i try to use stuff like color , Background , My app just crashes

**Comment by edenman** [comment]
You can use `app:tsquare_dayBackground="@drawable/custom_calendar_bg_selector"`, or if you'd prefer programmatic solution, add a CalendarCellDecorator.

**Comment by BbosaH** [comment]
Thankx alot
