### ISSUE TITLE
How to show first view is today ?

### ISSUE THREAD

**Issue by akmalshukri** [square/android-times-square#404]
I do selectionMode.Range .. the minimun date i set as last two month and maximum date is next 1 years, and when show calendar , it show for last month first .. 

example
Today is 5 nov..

it show September .. then need to scroll to see current date ..

**Comment by akmalshukri** [comment]
ok solved

**Comment by lamtan92** [comment]
hi @akmalshukri ,
I got same issue.
could you please show me how to solve this issue?
Thank you :)

**Comment by akmalshukri** [comment]
final CalendarPickerView calendar_view = (CalendarPickerView) alertLayout.findViewById(R.id.calendar_view);
//getting current
        Calendar last4Month = Calendar.getInstance();
        last4Month.add(Calendar.MONTH, -4);

        Calendar nextYear = Calendar.getInstance();
        nextYear.add(Calendar.YEAR, 1);
        Date today = new Date();

        calendar_view.init(last4Month.getTime(), nextYear.getTime())
                .inMode(CalendarPickerView.SelectionMode.RANGE)
                .withSelectedDate(today);
