### ISSUE TITLE
Custom format for calendar title

### ISSUE THREAD

**Issue by juanjecilla** [square/android-times-square#405]
Hi, 
I am trying to change the current format of the tilte that is shown above each month. Currently the format is January 2017 for example. I want to choose if the year is visible or not and also could change the month to the short format JAN. It is possible in the current version?

Thanks.

**Comment by edenman** [comment]
Yup!  You just need to define `<string name="month_name_format">MMM</string>` in both your `values` and `values-v9` directories.

**Comment by juanjecilla** [comment]
Hi thanks for the quick reply, works fine for the format but it is not capitalized, should I add something else?
Thanks!

**Comment by edenman** [comment]
Capitalization is entirely up the locale. afaik there's no way to specify capitalization in a DateFormat, but check out https://developer.android.com/reference/java/text/DateFormat.html to confirm
