### ISSUE TITLE
It set decorator in other date even not equals ?

### ISSUE THREAD

**Issue by akmalshukri** [square/android-times-square#408]
I implement CalendarCellDecorator and used setDecorators(decoratorList)

`for(int i = 0; i< arrayDateHaveJob.size(); i++){
       decoratorList.add(new EventDecorator(arrayDateHaveJob.get(i), Color.GREEN));
   }`

`public EventDecorator (Date evd, int BackgroundColor) {
        this.evd = evd;
        this.BackgroundColor = BackgroundColor;
    }

    @Override
    public void decorate(CalendarCellView calendarCellView, Date date) {
        if (date.equals(evd)) {
           calendarCellView.setBackgroundColor(BackgroundColor);
        }
    }`

My arrray date like this. 
[Mon Nov 06 00:00:00 GMT+08:00 2017, Thu Nov 02 00:00:00 GMT+08:00 2017]

Then i show different background (green color) for this date. It worked. But in other month also have (green color). Example on February 1 and 5 .. on May 3 and 7 .. look like either it plus one date or it minus one date from array date.

**Comment by akmalshukri** [comment]
@da3mon @xaviershay @eventualbuddha @emerose @cephus .. can someone help me ? thanks guys..

**Comment by JakeWharton** [comment]
Please do not mention random people. This is not a support forum. Someone
will reply when they have time.

**Comment by akmalshukri** [comment]
@JakeWharton i am sorry ... i delete that mention .. i thought can mention .. sorry again ..

**Comment by edenman** [comment]
You need to have an `else` block and un-set the background color

**Comment by akmalshukri** [comment]
I already put like this 

if (date.equals(evd)) {
calendarCellView.setBackgroundColor(BackgroundColor);
}
else {
calendarCellView.setBackgroundColor(otherColor);
}

date after first date , all dont have the icon ..
let say have 3 date , 20-11-2017,27-11-2017 and 29-11-2017 .. 

These two date 27-11-2017 and 29-11-2017 dont be backgroundColor (it be otherColor).
