### ISSUE TITLE
How to round the beginning and end of a selected range?

### ISSUE THREAD

**Issue by jglanfield** [square/android-times-square#419]
I've seen examples of where this has been done, but not sure if I need to create a decorator or something. Basically, I want the beginning and end dates of a selected range to have their selections rounded, like here:

https://github.com/square/android-times-square/issues/377

**Comment by edenman** [comment]
I _think_ you can do this just by using `tsquare_state_range_last` et al.  If that ends up being infeasible, you can implement a `CalendarCellDecorator` or if you need even more control, `DayViewAdapter`.

**Comment by jglanfield** [comment]
But isn't tsquare_state_range_last a boolean?

**Comment by edenman** [comment]
Yup, but it's an attribute to be used in a selector:
https://github.com/square/android-times-square/blob/master/sample/src/main/res/drawable/custom_calendar_bg_selector.xml

So you'd basically have your rounded corner background drawable, and use it when `tsquare_state_range_last` etc are true

**Comment by jglanfield** [comment]
Thanks :)

**Comment by jglanfield** [comment]
Never mind. Ordering matters. All good. Appreciate your help with this!
