### ISSUE TITLE
Disabling specific dates allows the selection range to cover the disabled dates

### ISSUE THREAD

**Issue by alexrosenfeld10** [square/android-times-square#420]
The calendar allows for a range to extend around disabled dates. The dates do not get selected, but there is not api for disallowing selections that contain disabled dates.

**Comment by alexrosenfeld10** [comment]
Followup.. I've written some nasty hacks to handle this. It'd be nice if it was a setting in the calendar api though.

**Comment by edenman** [comment]
https://github.com/square/android-times-square/blob/master/library/src/main/java/com/squareup/timessquare/CalendarPickerView.java#L1070
