### ISSUE TITLE
Can't set the max and min date one day apart

### ISSUE THREAD

**Issue by BinarSkugga** [square/android-times-square#427]
I can't seem to be able to set the maximum and minimum date one day apart when max is in another month.

I initialize the widget this way:
```java
Calendar nextDay = Calendar.getInstance();
nextDay.add(Calendar.DAY_OF_MONTH, 1);

final CalendarPickerView calendar = (CalendarPickerView)v.findViewById(R.id.mainDialogDatePicker);
Date today = new Date();
calendar.init(today, nextDay.getTime())
    .withSelectedDate(today);
```

**Comment by edenman** [comment]
what do you mean by "can't seem to be able to"

**Comment by BinarSkugga** [comment]
Using the calendar, setting the minimum date the 28 of february and the max at the first of march only let me choose the 28. I can't change the month.

**Comment by edenman** [comment]
From the `init` docs:
```   * @param minDate Earliest selectable date, inclusive.  Must be earlier than {@code maxDate}.
   * @param maxDate Latest selectable date, exclusive.  Must be later than {@code minDate}.
```
If you want to just today/tmw selectable, you need to do `nextDay.add(Calendar.DAY_OF_MONTH, 2)`
