### ISSUE TITLE
                                                                              java.lang.IllegalStateException: Must have at least one month to display.  Did you forget to call init()?                                                                                   at .timessquare.CalendarPickerView.onMeasure(CalendarPickerView.java:541)

### ISSUE THREAD

**Issue by akshaynjain** [square/android-times-square#431]
java.lang.IllegalStateException: Must have at least one month to display.  Did you forget to call init()?
                                                                                  at .timessquare.CalendarPickerView.onMeasure(CalendarPickerView.java:541)

When i am trying to implement it in Fragment, i am getting this error.

**Comment by edenman** [comment]
Please post the code you're using to initialize the `CalendarPickerView`

**Comment by akshaynjain** [comment]
Here is my Code, it's a fragment

public class CheckInFragment extends Fragment {
public CalendarPickerView calendarPickerView;


@Override
public void onCreate (Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
}

@Override
public View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
	// Inflate the layout for this fragment
	 View view = inflater.inflate(R.layout.fragment_check_in, container, false);
		calendarPickerView = (CalendarPickerView) view.findViewById(R.id.calendar_view);
		final Calendar nextYear = Calendar.getInstance();
		nextYear.add(Calendar.YEAR, 1);
		final Calendar lastYear = Calendar.getInstance();
		lastYear.add(Calendar.YEAR, -1);
		calendarPickerView.init(lastYear.getTime(), nextYear.getTime());
		calendarPickerView.setCustomDayView(new DefaultDayViewAdapter());
		calendarPickerView.setDecorators(Collections.<CalendarCellDecorator>emptyList());
		calendarPickerView.init(new Date(), nextYear.getTime())
				.inMode(CalendarPickerView.SelectionMode.SINGLE)
				.withSelectedDate(new Date());
		calendarPickerView.setOnDateSelectedListener(new CalendarPickerView.OnDateSelectedListener() {
			@Override
			public void onDateSelected (Date date) {
			
			}
			
			@Override
			public void onDateUnselected (Date date) {
			
			}
		});
	return view;
}

@Override
public void onAttach (Context context) {
	super.onAttach(context);
}

@Override
public void onDetach () {
	super.onDetach();
}

}

**Comment by edenman** [comment]
That should be fine.  Although you're calling `init` twice, which is unnecessary.  What's the full stacktrace of the error?  I'm guessing you might have another CalendarPickerView somewhere that you're not initializing?

**Comment by akshaynjain** [comment]
Thank you edenman,

Issue solved, as you said i have one more CalendarPickerView in another fragment in same activity.

Great observation

Thanks a lot

**Comment by Bukhari386** [comment]
@akshaynjain Hello,
What did you do to resolve the issue. Did you use init() only once? I have got the same scenario as yours.
Thanks.
