### ISSUE TITLE
Scroll to "week display" of currently selected date

### ISSUE THREAD

**Issue by veenahuddar** [square/android-times-square#435]
Hello,
This is not issue, but a clarification on whether is it possible to scroll to "week display" of the currently selected date instead of entire "month display", as shown in the screenshot below:
![current_week_display](https://user-images.githubusercontent.com/24404812/38912983-0aa9e340-42f6-11e8-8cb7-b54dae712d81.png)

**Comment by edenman** [comment]
We don't currently have a "week" display mode, no.

**Comment by veenahuddar** [comment]
Thank you for the quick response @edenman.

**Comment by chnouman** [comment]
@edenman  @veenahuddar how to show only few dates in month?
