### ISSUE TITLE
CalendarCellView height

### ISSUE THREAD

**Issue by Shakezulla57** [square/android-times-square#437]
I've implemented a `DayViewAdapter` and layout, but I seem to be unable change the height of the cell. Is this possible or is it always going to be a square? I'm looking to have the cell be taller than it is wide.

**Comment by edenman** [comment]
Currently not possible: `CalendarGridView.onMeasure` specifies that cell height == width / 7.  This is the first time I can remember anybody asking about this, but it does seem like a reasonable request.  Lemme see if I can fix it real quick.

**Comment by edenman** [comment]
Yup, got it.  I'm on an airplane rn, I'll publish a release tomorrow when I have real wifi again.  It's merged to master if you want to point at the snapshot and test it out.

**Comment by edenman** [comment]
Nevermind, the upload finished.  1.7.9 should be live shortly.

**Comment by Shakezulla57** [comment]
Awesome, thanks.
