### ISSUE TITLE
Date selected issue

### ISSUE THREAD

**Issue by ramesh4498** [square/android-times-square#443]
How to avoid deselecting all while third click.

Example

Assume Departure 15 may 2018 already selected.
Click return date 18 may 2018. So in between all the dates are highlight.
May be return date 18 may 2018 is wrong.so user selects 20 may 2018. At That time previously all highlighted dates are deselected.i need instead of deselecting 16 may 2018 to 20 may 2018 should highlighted.

Please help me

**Comment by edenman** [comment]
That's not how it works currently.  Feel free to add an interceptor with `setCellClickInterceptor` and then call selectDate in the permutations you want.
