### ISSUE TITLE
Cannot change selected date background Color

### ISSUE THREAD

**Issue by waseem786** [square/android-times-square#445]
I am using version 1.7.5
When I use 'tsquare_dayBackground' is change the background color of both selected and not selected dates. 
What I am expecting is, I want to use one background color to not selected date and another background color to selected dates.
Is there any method ?

**Comment by edenman** [comment]
You're on the right track: you want a `tsquare_dayBackground` but define it as a selector to switch between selected/normal/otherStates: https://github.com/square/android-times-square/blob/master/sample/src/main/res/drawable/custom_calendar_bg_selector.xml

**Comment by waseem786** [comment]
Thanks for your respond, I got it
