### ISSUE TITLE
On click for a selected date

### ISSUE THREAD

**Issue by waseem786** [square/android-times-square#446]
Hi, 
I am setting some dates from an Array with 'withSelectedDates(myDateArray)' function.
When I click an above selected date, clicked date background color changing back to normal (un selecting the date).
But what I want is, when I click a selected date,without  not selecting, show a toast message ' You pressed selected date ' and when I click not selected date, without selecting that date show a toast message ' You presses not selected date '.

I there any way to achieve this?

**Comment by edenman** [comment]
`setCellClickInterceptor`

**Comment by waseem786** [comment]
Thanks 👍
