### ISSUE TITLE
Different background colours based on condition

### ISSUE THREAD

**Issue by BilalMH** [square/android-times-square#462]
Is it possible to decorate each cell based on a condition I have? i.e. one day have the background of a cell purple and the other day black?

**Comment by edenman** [comment]
You can implement a `CalendarCellDecorator` or if you need even more control, `DayViewAdapter`.

**Comment by BilalMH** [comment]
Thanks @edenman , but I'm unsure how to use the CalendarCellDecorator, can you give me an example of how it's used?

Thanks
