### ISSUE TITLE
scrollToDate() can't be used with fixDialogDimens()

### ISSUE THREAD

**Issue by pleasespammelater** [square/android-times-square#463]
I'm trying to use scrollToDate() in a dialog. But it doesn't work if I am using fixDialogDimens() as shown in the sample code. If I remove the call to fixDialogDimens(), then scrollToDate() works fine.

Actually, the control seems to work fine without fixDialogDimens(), so is it really needed?

**Comment by edenman** [comment]
The original issue that caused `fixDialogDiamens()` to be added was #65.  Circa 2013.  If the widget is working fine without that method, definitely feel free to not use it :)

**Comment by pleasespammelater** [comment]
Okay... Thanks for the history!
