### ISSUE TITLE
Hide dates from previous/next month in current month

### ISSUE THREAD

**Issue by BilalMH** [square/android-times-square#465]
Is there a way to hide the dates from the previous/next in the month's calendar? Just to have the background of the cell and nothing else? 

Thanks

**Comment by edenman** [comment]
You can implement a `DayViewAdapter` and just hide the text view.

**Comment by AbdelrahmanSalahDeveloper** [comment]
can you put the portion code for this please

**Comment by dandar3** [comment]
Having to do the same I started from @edenman's sugestion and I found the samples activity where you can use either a custom `DayViewAdapter` or even a custom `CalendarCellDecorator`. 

https://github.com/square/android-times-square/blob/master/sample/src/main/java/com/squareup/timessquare/sample/SampleTimesSquareActivity.java

The less obvious part was I had to dig into `CalendarCellView` for was the check with `calendarCellView.isCurrentMonth()`, e.g.

```
private class CustomCellDecorator implements CalendarCellDecorator {
	@Override
	public void decorate(CalendarCellView calendarCellView, Date date) {
		if (!calendarCellView.isCurrentMonth()) {
			calendarCellView.getDayOfMonthTextView().setVisibility(View.INVISIBLE);
		}
	}
}
```
