### ISSUE TITLE
Day of week is off by one by one day when using the timezone is set on automode

### ISSUE THREAD

**Issue by kidsh3148** [square/android-times-square#485]
Hello Team, 

We are facing an issue for the day off for the calendar by one day when the timezone is set to AUTO mode in Samsung S7. Even after the few hours calendar is showing the perfect dates with days.

For your reference, I am attaching the screenshot for the issue with device's calendar and selected timezone.

<img width="301" alt="mon_g_1" src="https://user-images.githubusercontent.com/39192503/52477228-30e04080-2bc7-11e9-891b-48ab824f72ec.png">
<img width="300" alt="mon_g_2" src="https://user-images.githubusercontent.com/39192503/52477229-30e04080-2bc7-11e9-8dc5-4ca7f8adc955.png">
<img width="299" alt="mon_g" src="https://user-images.githubusercontent.com/39192503/52477230-30e04080-2bc7-11e9-9228-5bc23e8d4e27.png">

**Comment by hassan963** [comment]
Hi @kidsh3148, I am also having this issue. Did you solved this issue yet? needed some help. Thanks in advance.
