### ISSUE TITLE
Title for month and year doesn't show in dark theme

### ISSUE THREAD

**Issue by vahan8** [square/android-times-square#487]
![Screenshot_20190419-110709](https://user-images.githubusercontent.com/3892555/56411939-89048480-6293-11e9-8f23-dec4b1940291.png)

**Comment by MonikaJethani** [comment]
@edenman Is this resolved? Can I work on this?

**Comment by herberlin** [comment]
To solve this issue you may copy the styles definition of the CalendarTitle to your styles.xml in your resources folder and add the definition of the text-color. 

The original title  style can be found here: 
https://github.com/square/android-times-square/blob/master/library/src/main/res/values/styles.xml
Copy it into your styles.xml.

```
<style name="CalendarTitle">
    <item name="android:textSize">@dimen/calendar_text_medium</item>
    <item name="android:textStyle">bold</item>
    <item name="android:gravity">center_horizontal</item>
    <item name="android:paddingBottom">@dimen/calendar_month_title_bottommargin</item>
    <item name="android:paddingTop">@dimen/calendar_month_topmargin</item>
        
     <!-- add this line for the title color -->
     <item name="android:textColor">@color/calendar_text_active</item>

  </style>
```

Add the last line to set the text-color. In this case this is done by referencing one of calendars color - definiitons, but you may use any defined color here.
