### ISSUE TITLE
Dialog Fragment

### ISSUE THREAD

**Issue by seanyc4** [square/android-times-square#491]
Is there any guidance anywhere on the internet to set up this calender inside a dialogue fragment?

**Comment by JakeWharton** [comment]
No. The widget is a ListView so it doesn't care what type of presenter/controller/thing that you use.

**Comment by seanyc4** [comment]
It would be useful for people to show how it can be implemented.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by JakeWharton** [comment]
It's the same as any other DialogFragment or Dialog that displays a view.
There's nothing specific to the library.

**Comment by seanyc4** [comment]
When you put the ordinary default DatePicker in a dialog fragment you must return

return new

DatePickerDialog(getActivity()

,

(DatePickerDialog.OnDateSetListener) getTargetFragment()

,

year

,

month

,

day)

;"

When I copy and paste the code in to make your library work I don't know what I'm supposed to return to make it popup in the dialog when called and pass the year, month, day. It's not the same process as the default android DatePicker.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
