### ISSUE TITLE
CalendarCellDecorator, onDecorate is modifying cells from different months

### ISSUE THREAD

**Issue by naaaas** [square/android-times-square#494]
Hi. I have a calendar showing a complete year. I have an array with some dates that i want to highlight using decorator. When i set background color it highlights the "same" cells but on different months. Cellview seems to point to more than one cell within current year

            CalendarCellDecorator decorator= new CalendarCellDecorator() {
                @Override
                public void decorate(CalendarCellView cellView, Date date) {
                        if(diasFestivos.contains(date)){
                            cellView.setBackgroundColor(getResources().getColor(R.color.azulComeApp));
                            Utiles.logd(cellView.toString());
                        }else{
                            //Utiles.logd(date.toString());
                        }
                }
            };
            List<CalendarCellDecorator> decoratorList = new ArrayList<>();
            decoratorList.add(decorator);

            datePicker.setDecorators(decoratorList);

**Comment by edenman** [comment]
Cells are reused.  You need to put `cellView.setBackgroundColor(getResources().getColor(R.color.normal_cell_background_color));` in the else block.

**Comment by naaaas** [comment]
Yes!. Thank you

**Comment by xeissan** [comment]
I spent the best part of a morning investigating why my overly complex image decorators were decorating "random" cells, but only when retuning via **back navigation** to a fragment via the onResume.  Confused somewhat by decorators not being able to set backgrounds without scaling issues after 1.7.3....However
Resolved simply with an **if (cellView.background.isFilterBitmap); cellView.background = null** once it was clear the cells were being reused, thank you.
