### ISSUE TITLE
Date and day name of week not correct

### ISSUE THREAD

**Issue by ash-wtag** [square/android-times-square#503]
Hi, I am having this issue where the day name of January 2021 first is Friday but it's showing Thursday as First day of January 2021. It was working properly before, but I am not sure what's the issue here now. can you please help here, thank you.

<img src="https://user-images.githubusercontent.com/60562084/105623481-3a125880-5e44-11eb-9aff-02db7ace3ad9.png" width="250" height="400">

**Comment by edenman** [comment]
![Screen Shot 2021-01-25 at 09 18 57 ](https://user-images.githubusercontent.com/1063557/105642421-74d0cb00-5eee-11eb-9b7d-4cad118de990.png)
Showing correctly for me.  Sounds like maybe a locale issue, try hooking up the debugger and see if it's just formatting the "day name" headers wrong.

**Comment by ash-wtag** [comment]
Thanks for the hint @edenman , solved it. I was doing this for some reason, after removing -1, it works fine.
`int firstDayOfWeek = today.getFirstDayOfWeek() - 1;`
