### ISSUE TITLE
Abstract Compose View in CalendarCellView is causing jerk 

### ISSUE THREAD

**Issue by viceboyz** [square/android-times-square#517]
I have created an `ComposeTextView` extending `AbstractComposeView` and using Jetpack Compose `Text` internally. When using this `ComposeTextView` inside the `CalenderCellView`, it is causing jerk in calendar. Scrolling the calendar is too jerky.

**Comment by edenman** [comment]
Which version of Compose? There are perf issues with having N `AbstractComposeView`s, such as https://medium.com/androiddevelopers/jetpack-compose-interop-using-compose-in-a-recyclerview-569c7ec7a583

Regardless, it's probably a bad idea to use Compose with this library, it's not really set up for that.
