### ISSUE TITLE
1.7.11 version not found in sonatype

### ISSUE THREAD

**Issue by FazilButevApple** [square/android-times-square#521]
Hello,
I need 1.7.11 version package,i have been searched 1.7.11 version in sonatype but i can not found this version
Please share 1.7.11 version

**Comment by edenman** [comment]
https://mvnrepository.com/artifact/com.squareup/android-times-square/1.7.11

**Comment by FazilButevApple** [comment]
Eric hi,
The change made by our friend suleymanbilgin in version 1.7.11 is required for me, but when I pull the repository it does not work. What could be the reason?

https://github.com/square/android-times-square/commit/36e247f5beca6e47fd7c3866604a298c3dc0b9e6

Turkish translation of invalid date string (#515)
