### ISSUE TITLE
How to change the calendarview style?

### ISSUE THREAD

**Issue by bytebeats** [square/android-times-square#77]
Hi, there! thanks for your sharing.
You know, your times-square is very good and matches my style requirements. But it is still not friendly to change its face. If I want a more colorful view, do I have to change its styleable resource? Why not add some attributes to the CalendarPickerView?? like:
        android:background="#111155"
        android:firstDayOfWeek="1"
        android:focusedMonthDateColor="#009933"
        android:selectedWeekBackgroundColor="#55ffffff"
        android:showWeekNumber="true"
        android:shownWeekCount=""5

**Comment by RushiMThakker** [comment]
Can you please post the code?
