### ISSUE TITLE
Dates not highlighted until date clicked.

### ISSUE THREAD

**Issue by diyontheweb** [square/android-times-square#85]
Hi,

Not sure if an issue with my code or with the library. (Great library by the way). I believe this may be an issue.

Here's what I'm doing to initialise the calendar.

        calendar.init(lastYear.getTime(), nextYear.getTime()).inMode(SelectionMode.SINGLE).withSelectedDate(new Date()).withHighlightedDates(dates);

When the fragment loads, it isn't highlighted by default, but when a date is clicked, then it all the dates which are to be highlighted show correctly.

Thanks.

Edit #2:

Seems to be dependent on screen size. The issue occurred when using dates, that were 1 year apart, when only 2 months apart or less no issue occurs.

For example, I'm on a Nexus 4, displaying Oct 2013 -> Feb 2014 works perfectly which is 5 months. Anything more then this for my screensize, then the highlighted dates show on the wrong months. And on higher resolution devices which can fit more calendar months on a single view, it can take more months while still displaying correctly.

**Comment by omamapk** [comment]
I am unable to highlighted the multiple dates:

dateCalendar.init(today, nextYear.getTime()).inMode(CalendarPickerView.SelectionMode.SINGLE).withSelectedDate(new Date()).withHighlightedDates(highlightedDateList);

please, see what i am doing wrong?

**Comment by edenman** [comment]
Wow, this is an old issue.  Closing out since I assume @diyontheweb has moved on.  @omamapk file a new issue if you still have a problem.

**Comment by kamalahmedshaikh** [comment]
@edenman 
hii, how i can show previous selected date in calendar with range
